### ISSUE TITLE
boardwalk map Bug that can't end.

### ISSUE THREAD

**Issue by woong8848** [nmrih/source-game#1170] opened 2021-01-29 08:36 UTC
hi, first of all, I am a user who plays in korea.  So please understand if it's not grammatically correct.
I've just started this game, This game is really fun.
Let me explain the bug I experienced during the play.
while I was playing boardwalk map, We've reached the ending point of the helicopter ride.
But there's a bug in the helicopter where the rope won't come down.
The same problem repeats over and over again after finishing the game.
It's hard to make it to the end, but I can't do it because of the bug.
I wonder if this problem is happening only to me.
Thank you for listening to my problem. Have a nice day!

**Comment by felis-catus** [comment] 2021-01-29 08:39
Duplicate of #1169.

**Closed by felis-catus** 2021-01-29 08:39 UTC
