### ISSUE TITLE
Nametag bug

### ISSUE THREAD

**Issue by TeXnoFile** [nmrih/source-game#734] opened 2015-05-24 21:52 UTC
Version: NMRIH 1.9.4 (It has been happening since the 1.9.2)

What happens: From time to time,when players die, their name stays shown in the map and doesnt disappear till they spawn again. This might even happen when players are alive. Their names get randomly stuck somewhere in the map, and when you come there there is no player just his/hers name, then the name moves to the proper spot above players head.

When does it happen: Randomly, all servers, all maps

Steps to reproduce the issue: N/A
Screenshots:
![2015-05-24_00001](https://cloud.githubusercontent.com/assets/12586797/7789832/c7d9deea-026f-11e5-8dab-4c9fcd478392.jpg)

Youtube fraps captures of the issue:N/A
Developer Console Output: N/A
System information:N/A

**Comment by Fersigal** [comment] 2015-05-25 12:58
These are very common though, i had them to and i keep seeing them often somehow when i play. It's really annoying

**Comment by Bubka3** [comment] 2018-01-22 20:58
Duplicate of #639 

Please follow that issue for all further tracking.

**Closed by Bubka3** 2018-01-22 20:58 UTC
Labels: code, duplicate, reviewed
