### ISSUE TITLE
nmo_toxteth spawn doors jam trap

### ISSUE THREAD

**Issue by x5566asd** [nmrih/source-game#722] opened 2015-04-11 16:51 UTC
Version: 1.09.4 or older version
What happens: people get stuck and never leave
When does it happen: When the door open toward you
Steps to reproduce the issue: simple press E few times
![2015-04-11_00001](https://cloud.githubusercontent.com/assets/11902227/7102250/2a211120-e0ad-11e4-9a53-0bffd70bad09.jpg)

I think this is all you need to know about this

**Comment by Bubka3** [comment] 2018-01-18 16:12
Duplicate of #716

**Closed by Bubka3** 2018-01-18 16:12 UTC
Labels: map, reviewed
