### ISSUE TITLE
[nmo_cabin] 1.07.9 Bugs

### ISSUE THREAD

**Issue by grasn** [nmrih/source-game#545] opened 2014-03-09 06:08 UTC
kitchen lock floating in the air:
![nmo_cabin0012](https://f.cloud.github.com/assets/5090011/2367279/06c87e7a-a751-11e3-8ccf-57db5d9cce38.jpg)

the red outline of the door was already opened, before we put in the key:
![nmo_cabin0013](https://f.cloud.github.com/assets/5090011/2367280/0e09e368-a751-11e3-9ff8-f36f15b57de0.jpg)

**Comment by Fersigal** [comment] 2018-01-18 17:08
Kitchen lock still floats in the air, not sure about the glow though, i think that one's fixed

**Comment by AtheistNMRiH** [comment] 2018-02-08 11:14
glow still appears sometime, mainly a code issue, happens on other maps too, but I couldn't reproduce it

**Comment by Bubka3** [comment] 2018-02-09 09:12
I believe this is something that might be corrected by recent glow changes in the dev build, but tagging @felis-catus for further review.

**Comment by AtheistNMRiH** [comment] 2018-02-16 16:45
fixed kitchen lock floating in the air in r8729

**Comment by Bubka3** [comment] 2018-02-26 19:04
Glow implementation was re-done. Marking as completed for QA testing.

**Comment by Holycrapjimhox** [comment] 2018-03-31 02:04
Confirmed fix in src-4388/r-8769. Needs to be closed.

**Closed** 2018-03-31 02:35 UTC
Labels: Priority: Normal, Status: Completed, Type: Code
