### ISSUE TITLE
TSAROUHAS voice set missing closedcaption

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#861] opened 2018-02-18 12:58 UTC
my apologize, I guess I used wrong termin
anyway, looks like problem is on public build too
![m60deployed_gun0000](https://user-images.githubusercontent.com/11333747/36419181-c326736c-1663-11e8-9ab3-86f551c44969.jpg)

now I'm not sure if it is supposed to be closecaptions for "plenty of magazines" on all voice sets, if no, then that is not a bug

TSAROUHAS hasn't any of closecaption
1) choosing command Follow me -> no closecaption
![m60deployed_gun0002](https://user-images.githubusercontent.com/11333747/36419114-98a1144e-1663-11e8-9d88-aa7fec776dfd.jpg)
![m60deployed_gun0003](https://user-images.githubusercontent.com/11333747/36419119-9bdecc64-1663-11e8-8eec-7c7d865e714d.jpg)
2) reloading -> no closecaprtion
![m60deployed_gun0004](https://user-images.githubusercontent.com/11333747/36419170-b6ad99c6-1663-11e8-9f91-87cf1fb29358.jpg)
and etc

what I expected to see:
![m60deployed_gun0000](https://user-images.githubusercontent.com/11333747/36419313-1c619da8-1664-11e8-90ea-1a50cfeabcb3.jpg)

**Comment by Bubka3** [comment] 2018-02-20 03:24
I cant reproduce this. Can you better explain what is missing and what you expect to see, with screenshots?

**Comment by AtheistNMRiH** [comment] 2018-02-20 03:39
sure, i'll do it in few hours

**Comment by AtheistNMRiH** [comment] 2018-02-20 10:34
check first comment

**Comment by Bubka3** [comment] 2018-02-20 15:22
This is a translation issue. I will take care of it.

**Comment by Bubka3** [comment] 2018-02-23 22:41
![](https://github.trello.services/images/mini-trello-icon.png) [TSAROUHAS voice set missing closedcaption](https://trello.com/c/mVNB3wgE/143-tsarouhas-voice-set-missing-closedcaption)

**Comment by Winning117** [comment] 2018-04-05 08:03
Taunt is missing closed captions for English so not entirely a translation issue. Tested in src-r4405/dev-r8773.

**Comment by Bubka3** [comment] 2018-04-05 16:27
Taunt doesn't have closed captions because it doesn't exist in the translation file. It doesn't exist in the translation file likely because our closed captions are not true. We show a generic message of what the line should say instead of what the audio actually says for any given lines. This might work for stuff like [Follow me!], but the taunts are all different. We couldn't just make the closed caption for it [Taunt!].

**Comment by felis-catus** [comment] 2022-10-19 16:51
Resolved by https://github.com/nmrih/nmrih-localization-files/pull/57, thanks to [Plazehorta](https://github.com/Plazehorta)!

**Closed by felis-catus** 2022-10-19 16:51 UTC
Labels: Type: Assets, Priority: Normal, Status: Assigned
