### ISSUE TITLE
Locations you can throw objective items outside of most objective maps

### ISSUE THREAD

**Issue by CoolR** [nmrih/source-game#803] opened 2016-06-04 13:05 UTC
So, I found various locations you can get map objectives (such as keys, gas tanks, ect) into a part of the map where they cannot be recovered. I've documented the locations in which they can get stuck, and why.

First off is Toxteth.

![nmo_toxteth0017](https://cloud.githubusercontent.com/assets/19744235/15799368/1624fa2c-2a0f-11e6-924b-411d1c7a2c93.jpg)

At the very beginning of the map, the area you blow up with the gas tank lacks clipping preventing physics objects from passing above them, and due to this, it is incredibly easy to break the level immediately. (It isn't that wall specifically-- most of the walls in that area lack physics clipping, that is just an example.)

![nmo_toxteth0023](https://cloud.githubusercontent.com/assets/19744235/15799373/7756064c-2a0f-11e6-9660-aec1e275d9b3.jpg)

Directly after that, you can take the TNT and, since the physics clip doesn't extend the entire way, drop it behind that fence, never to be retrieved.

![nmo_toxteth0027](https://cloud.githubusercontent.com/assets/19744235/15799383/b155f0b4-2a0f-11e6-8e54-39db58e98fb0.jpg)

![nmo_toxteth0025](https://cloud.githubusercontent.com/assets/19744235/15799411/a5d02a1a-2a10-11e6-9189-0ab9aa9d9236.jpg)

You can also take the TNT to the rightmost walls of the cemetery, and, since the bars aren't solid, the TNT passes right through them, and can be dropped outside the map with ease.

![nmo_toxteth0029](https://cloud.githubusercontent.com/assets/19744235/15799392/1273fff8-2a10-11e6-8a02-1bc19492edaf.jpg)

Speaking of non-solid bars, at the beginning of the map, once again, the bars aren't solid and the gas can can be dropped outside the map.

![nmo_toxteth0032](https://cloud.githubusercontent.com/assets/19744235/15799399/3da72de4-2a10-11e6-929b-c85e19cffd99.jpg)

On to the store, because of the way the ceiling is designed, you put the key directly above the room you're supposed to unlock with it.

![nmo_toxteth0031](https://cloud.githubusercontent.com/assets/19744235/15799404/6b513ad2-2a10-11e6-8aca-855a45fc42cc.jpg)

In this photo, the key isn't actually stuck forever, however, since most people don't look up when looking for a key, people most likely will never find the key if it's put there.

Broadway isn't as broken, though. It certainly has its quirks however.
![nmo_broadway0015](https://cloud.githubusercontent.com/assets/19744235/15799431/1a8af902-2a11-11e6-9c42-bd15a7e9c965.jpg)

At the very beginning of the level, the fence behind the spawn building doesn't have physics clipping to prevent players from throwing objective items behind it.

![nmo_broadway0035](https://cloud.githubusercontent.com/assets/19744235/15799438/731bef22-2a11-11e6-927b-ea0f6faef189.jpg)

Right by the diner, the physics clipping doesn't extend completely from both sides of the street, which leads to people being able to lose batteries or propane behind that fence. 

![nmo_broadway0036](https://cloud.githubusercontent.com/assets/19744235/15799445/aa7c0f60-2a11-11e6-892e-8dd9618b7a17.jpg)

At the bar's basement, you can put the key up there, where it can't be grabbed. 

![nmo_broadway0038](https://cloud.githubusercontent.com/assets/19744235/15799448/cb06cb3a-2a11-11e6-81f0-a714965a0879.jpg)

This fence by the bar also lacks physics clipping.

Cleopas is pretty easy to break by putting objectives outside the map.

![nmo_cleopas0043](https://cloud.githubusercontent.com/assets/19744235/15799462/3579952e-2a12-11e6-9889-ec16a61e60da.jpg)

At the beginning of the level, with precise placement of the TNT, you can get it stuck inside the window frame, however that takes quite a bit of effort.

![nmo_cleopas0044](https://cloud.githubusercontent.com/assets/19744235/15799466/535e9e22-2a12-11e6-953e-0c6e6e96bd1e.jpg)

However, if you want to softlock the game with much less effort, you can put the TNT behind this door and it, just barely, can't be grabbed from any position short of boosting a player up. (I've tried to get it for 10 minutes, so yeah, it definitely can't be grabbed)

![nmo_cleopas0045](https://cloud.githubusercontent.com/assets/19744235/15799468/7f0063e4-2a12-11e6-8d0b-2cf7498f02f7.jpg)

Moving on to why cleopas is pretty broken, basically you can lose the pliers on almost every one of those models, unless there is something large enough to jump onto to get up. Otherwise, if someone puts the pliers (or any small enough objective item) up there, its gone.

![nmo_cleopas0052](https://cloud.githubusercontent.com/assets/19744235/15799483/e780c8dc-2a12-11e6-9387-31da57bbfe20.jpg)

You could also put the pliers back here, since the table is non-solid.

![nmo_cleopas0051](https://cloud.githubusercontent.com/assets/19744235/15799485/fdcdf218-2a12-11e6-8818-3d9b048921d3.jpg)

Or maybe you'd put it here.

![nmo_cleopas0053](https://cloud.githubusercontent.com/assets/19744235/15799487/08b05a2c-2a13-11e6-9a19-6d14cf740872.jpg)

While there is physics clipping play to prevent the pliers behind the locked gate, there are some gaps at the top of the fence which is just large enough to allow the pliers to go through it.

As for Junction, there was only one area in which I could put objective items outside the map-- the fire escapes. 

![nmo_junction0040](https://cloud.githubusercontent.com/assets/19744235/15799506/d727043c-2a13-11e6-82e6-edcc369d18b5.jpg)

As you can see, you can put the propane tank up onto the fire escapes, where they can't be taken back down. 

![nmo_junction0042](https://cloud.githubusercontent.com/assets/19744235/15799509/19bbb5ae-2a14-11e6-8076-22b2dd3db4f7.jpg)

Also, while this isn't broken, I think there should be clipping preventing players from bringing the key to the sewers, since I think a clueless player might take the key and run back with it, only to get it lost inside the sewers forever. Just a suggestion.

![nmo_brooklyn0061](https://cloud.githubusercontent.com/assets/19744235/15799517/a0e56f98-2a14-11e6-84ff-37e69744c910.jpg)
Moving on to Brooklyn, at the very beginning of the map, you can put the key underneath the soldier's corpse and get it stuck. (Which, to be honest, I doubt is fixable short of deleting the corpse, but I thought I'd put it here)

![nmo_brooklyn0066](https://cloud.githubusercontent.com/assets/19744235/15799535/f192c30a-2a14-11e6-814e-d4dd4a1a0dd4.jpg)

You can put the fuse behind this monitor, and get it stuck.

![nmo_brooklyn0071](https://cloud.githubusercontent.com/assets/19744235/15799553/5e000606-2a15-11e6-971c-2b12b84a149c.jpg)

You can also put the fuse underneath this desk (with some difficulty)

![nmo_brooklyn0069](https://cloud.githubusercontent.com/assets/19744235/15799558/7ceef73e-2a15-11e6-8569-b2051b186a3f.jpg)

While there is clipping to prevent people from climbing over the fallen shelve, it doesn't extend completely to the wall, and due to this you can actually put the fuse behind the file cabinets where it isn't grab-able.

![nmo_brooklyn0072](https://cloud.githubusercontent.com/assets/19744235/15799565/b0a0c2ec-2a15-11e6-8196-3883df8270ec.jpg)

As for the lock, if you go on top of the truck you're supposed to land on to break the fall, and jump towards the apartment window, you can slam dunk the lock back into the apartments and, if everyone has jumped down at that point, score a soft-lock.

![nmo_brooklyn0077](https://cloud.githubusercontent.com/assets/19744235/15799572/0a271064-2a16-11e6-891b-3992f5f512e4.jpg)

You could also put the lock behind the monitor in the office, but that isn't nearly as fun to do.

![nmo_brooklyn0080](https://cloud.githubusercontent.com/assets/19744235/15799580/2b0b509c-2a16-11e6-90f4-710e733e65ce.jpg)

Just as in Junction, you can put objective items onto most fire escapes, and with good positioning, they'll never come back down.

![nmo_brooklyn0081](https://cloud.githubusercontent.com/assets/19744235/15799586/5d334c5a-2a16-11e6-97ef-b438c690521b.jpg)

Further on, you can put the gasoline inside of this dumpster. 

![nmo_brooklyn0082](https://cloud.githubusercontent.com/assets/19744235/15799591/794ae4b6-2a16-11e6-9e32-0b6cae4d735f.jpg)

You can also put the gasoline behind this wall, as well.

![nmo_brooklyn0085](https://cloud.githubusercontent.com/assets/19744235/15799601/ab5232b6-2a16-11e6-9271-20ebe4eed376.jpg)

And since there isn't any physics clipping above the fence and walls, you can put the supplies inside of the quarantine before it's even opened!

And now for Fema, which is, no offense, probably the easiest official map to break

![nmo_fema0087](https://cloud.githubusercontent.com/assets/19744235/15799618/41a19338-2a17-11e6-8ba6-149d40405a2f.jpg)

Right as soon as you get the key-card, there are three different ways you can soft-lock the game, first off is by putting the card onto the far corner of this trailer, where it can't be grabbed.

![nmo_fema0088](https://cloud.githubusercontent.com/assets/19744235/15799626/70c8e832-2a17-11e6-9a16-2a99043edac5.jpg)

This second way is just, evil. Completely evil.
None of those barrels have any physics clipping anywhere, so the only thing stopping the key-card from getting stuck is the collision model, which has holes in it. You can put the key-card, as it is a small model, in with the barrels or on top of it. I put the card on top of the barrels as an example, but you can also slide the key-card in with the barrels, which, while it could be grabbed, putting the key-card there makes it extremely difficult to see, as the model is a two-dimensional plane,

![nmo_fema0090](https://cloud.githubusercontent.com/assets/19744235/15799654/3e43ab76-2a18-11e6-9961-495c1e6e7517.jpg)

As for the third way, you can also take the key-card and put it on top of the office building adjacent to the door it unlocks where people are unlikely to find it, as you have to jump up on a prop or the railing to even be able to get the key-card, and even then I doubt anyone really jumps up onto props once they learn how much of the props are clipped off, and I doubt anyone would jump onto the railing long enough to see it.

Honestly though, since the key-card is very small and there is a distinct lack of clipping in that area, I suggest you go through that area and rework the clipping.

![nmo_fema0092](https://cloud.githubusercontent.com/assets/19744235/15799672/eef76c50-2a18-11e6-8293-fe1a7a993740.jpg)

Much, much later in the level, when you have to bring the hand-crank  to the gate, since this dumpster isn't solid, with some effort, you can throw the crank into a corner in which it is impossible to get at.

Once players get topside, there are a few ways to get the key out of the map.

![nmo_fema0095](https://cloud.githubusercontent.com/assets/19744235/15799687/69415fb6-2a19-11e6-8e29-df8f7182ee20.jpg)

You can put the key onto this wall and move it behind the fence to the right, which isn't accessible.

![nmo_fema0096](https://cloud.githubusercontent.com/assets/19744235/15799704/8808c98e-2a19-11e6-84c5-563ff3e32068.jpg)

Since the wall in the earlier picture isn't clipped, you can put the key behind an open gate on display.

![nmo_fema0097](https://cloud.githubusercontent.com/assets/19744235/15799706/a75b0d7e-2a19-11e6-8d59-8defdd5f0cac.jpg)

I find this hole particularly surprising to not be clipped off.

**Comment by yomox9** [comment] 2016-06-05 02:19
Maybe tihs is problem, But I guess fix is too difficult.

**Comment by AtheistNMRiH** [comment] 2016-06-05 15:55
why? just put some finc_clip_vphysics in some places

**Comment by yomox9** [comment] 2016-06-06 02:06
for only this? .... Mapper need too many work( put func_clip_vphysics and test) for this . and It's not perfect. Probably, There are many other problem place.

If Mapper do it, Map's quality will be better than before. But mapper will can't make New map because too many work.

**Comment by CoolR** [comment] 2016-06-06 14:38
You know what, I'll do it myself. I'll go into the editor and fix everything and upload the vmfs.

**Comment by AtheistNMRiH** [comment] 2016-06-06 15:27
for only this? if someone will do something like that it will ruin all game

**Comment by CoolR** [comment] 2016-06-06 15:31
Exactly. Kicking in this game isn't efficient at all since there is no ban time from the server, so if someone gets kicked they can just rejoin, and they can very easily ruin everything.

**Comment by yomox9** [comment] 2016-06-07 03:16
That's right > AtheistNMRIH, CoolIR. But my assertion is not change.
> You know what, I'll do it myself. I'll go into the editor and fix everything and upload the vmfs.
Rightly, I don't think that your work is bad > CoolR. Good luck

**Comment by AtheistNMRiH** [comment] 2018-01-20 19:10
fixed fema related bugs (not in dev build)

**Comment by Bubka3** [comment] 2018-01-23 17:53
Coolz has fixed junction related bugs in dev build as of this comment

**Comment by AtheistNMRiH** [comment] 2018-02-05 07:30
fixed brooklyn related bugs in r8720

**Comment by AtheistNMRiH** [comment] 2018-02-08 11:44
fixed cleopas related bugs in r8721 and broadway in r8724

**Comment by AtheistNMRiH** [comment] 2018-02-17 16:41
toxteth issues are the same as in #850 , it is easier to me to follow last one, so current issue can be labeled as resolved

**Comment by Winning117** [comment] 2018-04-26 09:39
Confirmed fixed in src-r4405/dev-r8791, needs to be closed.

**Closed** 2018-05-01 15:14 UTC
Labels: Priority: Normal, Status: Completed, Type: Map
