### ISSUE TITLE
Movement laggy, exaggerated and out of sync with key presses

### ISSUE THREAD

**Issue by RickyFisher98** [nmrih/source-game#897] opened 2018-03-24 19:19 UTC
Hi,

Almost always when I click out of the game, then come back, my movement is horribly exaggerated and I keep moving for about a second after releasing the key. Nothing else except movement seems to be affected. Especially when you jump while running, it's almost as if you jump on the spot then shoot forward. 

The game is completely unplayable at this point as you can't move properly.

Killing yourself, having the map change or rejoining the server all fix the issue.

**Comment by Holycrapjimhox** [comment] 2018-03-24 19:21
Duplicate issue: https://github.com/nmrih/source-game/issues/350

Temporal solution: don't alt tab, don't start any demo recordings.

**Comment by Holycrapjimhox** [comment] 2018-03-24 19:26
"Saying you can't and won't fix the bug is pathetic. I'm not sure how character movement works in NMRIH, but you can certainly reset the movement engine and animations when the game receives focus."

Where did I say it won't be fixed? I only gave you a temporal solution because the bug is being investigated to find the proper fix. Check the tags on the original report and you'll see that it's assigned to a coder.

**Comment by RickyFisher98** [comment] 2018-03-24 19:26
I wasn't replying to you, I was replying to the person who said that.

**Comment by Holycrapjimhox** [comment] 2018-03-24 19:28
Nevermind, I thought you had posted here and eliminated the message.

**Comment by Bubka3** [comment] 2018-03-24 22:21
**Duplicate Closure**
This issue has been closed because it has already been reported under a previous issue ID.
Please follow the issue below for further updates.

Duplicate of #350

**Closed by Bubka3** 2018-03-24 22:21 UTC
