### ISSUE TITLE
[public-1.13.6] Random crashes on Linux

### ISSUE THREAD

**Issue by Isemenuk27** [nmrih/source-game#1520] opened 2024-10-04 03:32 UTC
Sometimes game simply exits without any logs or errors. This happens when advancing through maps objectives, right before "Next Objective" message appears.

**Comment by Isemenuk27** [comment] 2024-10-20 01:44
[crash_20241019183352_3.zip](https://github.com/user-attachments/files/17448033/crash_20241019183352_3.zip)
So crashing before objective was likely coincidence. Managed to get dump, after game crashed on nmo_toxteth on unmoded server.

**Comment by felis-catus** [comment] 2024-11-03 22:22
Duplicate of #1502

**Closed by felis-catus** 2024-11-03 22:22 UTC
Labels: OS: Linux, Status: Reviewed, Type: Crash, Priority: Minimal
