### ISSUE TITLE
Blowtorch doesn't extinguish when spectating

### ISSUE THREAD

**Issue by VaTTeRGeR** [nmrih/source-game#633] opened 2014-08-25 12:45 UTC
[Steam-Build, Dedicated Server]
The "blowtorch first person model sparkle effect" does not extinguish after welding, when spectating it's user; I didn't encounter this on a local game yet, only when playing online.
Pics:
![nmo_cleopas0000](https://cloud.githubusercontent.com/assets/5089550/4029767/cf95b1a0-2c54-11e4-9b08-493254ab7a79.jpg)
![nmo_cleopas0003](https://cloud.githubusercontent.com/assets/5089550/4029769/da7d5ece-2c54-11e4-8bad-78f26d222f41.jpg)

**Comment by Winning117** [comment] 2018-02-09 10:44
Same as [#778](https://github.com/nmrih/source-game/issues/778)

**Comment by AtheistNMRiH** [comment] 2018-02-09 11:51
these issues not the same, because I guess player C@m don't use it like you in your video, more a spectator bug

**Comment by Winning117** [comment] 2018-04-04 08:57
Confirmed fixed in src-r4388/dev-r8772, needs to be closed.

**Closed** 2018-04-04 08:58 UTC
