### ISSUE TITLE
FN-FAL graphical bug

### ISSUE THREAD

**Issue by chalermla24** [nmrih/source-game#768] opened 2015-10-05 19:01 UTC
[1.09.5]When zoom in(using toggle zoom) on fn fal and ammo check there will be a bullets in magazine even if ammo count in magazine is zero
edit: not just fn fal lots of other guns too

**Comment by x5566asd** [comment] 2015-10-06 08:57
#761 is the same problem. Hope it will be fixed soon.

**Comment by Bubka3** [comment] 2018-01-17 04:39
Duplicate of #761 -- please follow that issue for updates.

**Closed by Bubka3** 2018-01-17 04:39 UTC
Labels: duplicate, reviewed
