### ISSUE TITLE
[nmo_cabin] Significant framerate problem after joining game

### ISSUE THREAD

**Issue by Keldorn074** [nmrih/source-game#466] opened 2013-11-02 19:36 UTC
I clicked on Xendrids view game info and joined his nmo_cabin game and when I spawned into the attic I had 9 fps and stayed at 9 fps, I had to disconnect. 

Edit:

Actually, I think it could have been something to do with the main menu music that plays while in-game if using the Join game button from someone's steam profile thing.

![2013-11-02_00001](https://f.cloud.github.com/assets/3848484/1459776/19ea23b4-43f6-11e3-95e8-c0dcc7518154.jpg)

**Comment by AtheistNMRiH** [comment] 2018-02-09 09:26
I play since 2014 and never had this problem, maybe felis can say smth about that, but there is few info

**Comment by Bubka3** [comment] 2018-02-26 19:30
I cant reproduce this either and this is a very old ticket. Probably no longer an issue. Closing...

**Closed by Bubka3** 2018-02-26 19:30 UTC
Labels: Status: Reviewed, Type: Code, Type: Map
