### ISSUE TITLE
Gene Therapy "zoom-in" bug during partial blindness

### ISSUE THREAD

**Issue by yomox9** [nmrih/source-game#889] opened 2018-03-18 23:30 UTC
https://youtu.be/tFOud3Hu9PA
Version : 1.09.7
When use the Gene therapy, Player can't see anything.
Reproduce : Repeast use gene therapy

**Comment by Winning117** [comment] 2018-03-19 07:57
This isn't a bug, this is intended :p It's been in the game as long as gene therapy iirc

**Comment by yomox9** [comment] 2018-03-19 08:07
hmmmmm. I understand you said. But I really just looks like bug to me....

**Comment by Mateos81** [comment] 2018-03-19 08:09
This is intended because else that would be too easy to cure the infection... It does not happen every time, but can. It's a risk to take in case you no longer have pills.

**Comment by yomox9** [comment] 2018-03-19 08:41
ok. I understood it completely. But it is appear bug, because It just zoom in something.
So I suggest that add the effect like when infection to screen. Example, blood vessel ( or blue blood vessel)

**Comment by felis-catus** [comment] 2018-03-19 10:18
Oh, I should have watched the video first before jumping into conclusions, sorry about that.

While the partial blindness from gene therapy is a feature, this *zoom-in* is not. I have never encountered this before.

Please provide your video options and system information so I can take a closer look. Reopening.

**Comment by yomox9** [comment] 2018-03-19 10:35
Computer Information:
    Manufacturer:  MSI
    Model:  MS-7A74
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
    CPU Family:  0x6
    CPU Model:  0x9e
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3504 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Supported

Operating System Version:
    Windows 10 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  NVIDIA GeForce GTX 960
    DirectX Driver Name:  nvldumd.dll
    Driver Version:  23.21.13.8813
    DirectX Driver Version:  23.21.13.8813
    Driver Date: 10 27 2017
    OpenGL Version: 4.6
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    DirectX Card: NVIDIA GeForce GTX 960
    VendorID:  0x10de
    DeviceID:  0x1401
    Revision:  0xa1
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 20.04" x 11.26" (22.95" diag)
                                            50.9cm x 28.6cm (58.3cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 2047 MB
    Supported MSAA Modes:  2x 4x 8x 

Sound card:
    Audio device: RDT233WX-3D-4 (2- NVIDIA High D

Memory:
    RAM:  8157 Mb

Miscellaneous:
    UI Language:  English
    Media Type:  Undetermined
    Total Hard Disk Space Available:  10325774 Mb
    Largest Free Hard Disk Block:  3198195 Mb
    OS Install Date: 1 01 1970
    Game Controller: XInput Controller #1 detected
    VR Headset: None detected

---
![20180319192030_1](https://user-images.githubusercontent.com/14893069/37590716-7570b4a8-2bac-11e8-8679-bba31771436f.jpg)
![20180319192045_1](https://user-images.githubusercontent.com/14893069/37590726-79e47c4a-2bac-11e8-8179-2712f7ef581f.jpg)

**Comment by Bubka3** [comment] 2018-03-19 14:04
Just to clarify, it's intended that the user becomes blind for a set period time because the gene therapy mutated incorrectly. The zoom is not.

**Comment by Mateos81** [comment] 2018-03-19 14:13
Oh, after a while you can see again? Well I probably never lived long enough to see this :P
That zoom effect could be a little stressing moment like "Am I going blind?!" if the fix isn't easy

**Comment by DDysphie** [comment] 2018-03-19 17:09
I used to know the repro steps for this. It has to do with graphics settings. I'm pretty sure shaders (but could be shadows or something else). Setting it to low triggers the zoom.

Can't confirm because my PC straight out doesn't render blindness effects

**Comment by yomox9** [comment] 2018-03-20 01:57
> Oh, after a while you can see again?

Yes, I could see again today.
Procedure:
map nmo_broadway in client console.
sv_cheats 1 ( for get gene_therapy )
Use gene therapy x 7
sv_cheats 0
Use gene therapy x 3
**Bug**
Use gene therapy x 25
sv_cheats 1 ( for put gene_therapy )
sv_cheats 0
Use gene therapy x 13
**Bug**

Video setting is same as yesterday.
I can see this Bug in normal game. I saw it in version 1.09.6 too.

**Comment by Winning117** [comment] 2018-04-05 04:46
After messing around with the settings a bunch I was able to locate the cause of the zoom-in bug: setting Anti-Aliasing to "None" :D

**Comment by felis-catus** [comment] 2019-01-06 09:53
Resolved in src-r4692.

**Closed by felis-catus** 2019-01-06 09:53 UTC
Labels: Priority: Normal, Status: Assigned, Type: Code
