### ISSUE TITLE
[public-1.12.0] New maps bugs/feedback

### ISSUE THREAD

**Issue by TheUnstableNutcase** [nmrih/source-game#1239] opened 2021-11-01 19:05 UTC
====nmo_anxiety====

The fire looks a little bit weird here, coming over the edges and stuff:
![20211031215642_1](https://user-images.githubusercontent.com/42658874/139725112-e098a166-88b0-44dc-b6ff-261ab7f31767.jpg)

The particles when I punch this wood are broken:
![20211031215717_1](https://user-images.githubusercontent.com/42658874/139725207-a12a0f94-7b4c-44c5-87e6-bf9a39f704f9.jpg)

Missing texture here:
![20211031215753_1](https://user-images.githubusercontent.com/42658874/139725315-7f89f89b-8565-4b01-8a4c-a855966df3ee.jpg)

This locked bathroom door doesn't make any sound when you try to open it, whereas the one right next to it does:
![20211031220328_1](https://user-images.githubusercontent.com/42658874/139725446-0565a754-8bfd-4d4d-985e-9e227bb77042.jpg)

If this is supposed to take place somewhere in North America or possibly Europe, why are these signs and stuff in Chinese?
![20211031220544_1](https://user-images.githubusercontent.com/42658874/139725610-3dd927cf-9dca-4c8d-8500-d3eba1b93ed1.jpg)

![20211031220616_1](https://user-images.githubusercontent.com/42658874/139725637-58de7906-22ab-45a7-b665-f1566af77317.jpg)

Missing texture here:
![20211031221246_1](https://user-images.githubusercontent.com/42658874/139725752-b4533308-9cd1-4266-89bf-785ab5b46ee1.jpg)

====nmo_rockpit====

The grammar on this objective is really bad:
![20211031221859_1](https://user-images.githubusercontent.com/42658874/139725886-7a6a838b-2f3a-440b-adea-91c9b7230a2b.jpg)

Missing texture here:
![20211031222006_1](https://user-images.githubusercontent.com/42658874/139725936-7b110095-e906-4318-830d-b2a7e90be61c.jpg)

Players are expected to carry this gas can through this insanely dark tunnel, however if they have to carry an objective item, they can't use a flashlight or a lighter, so how are they even supposed to see? Zombies would be impossible to spot here. This area needs to be brightened up:
![20211031222033_1](https://user-images.githubusercontent.com/42658874/139726196-ceb9d99a-9904-4786-b283-e628ad42b342.jpg)

Missing texture here:
![20211031222120_1](https://user-images.githubusercontent.com/42658874/139726227-a2ed5ef1-60b5-4439-94e9-5bf439377d23.jpg)

The elevator doors didn't close here:
![20211031222232_1](https://user-images.githubusercontent.com/42658874/139726294-fe05ceb3-5d49-423b-a522-c7124373fb34.jpg)

Missing texture here:
![20211031222415_1](https://user-images.githubusercontent.com/42658874/139726352-8d5c521d-a495-4ff3-a996-122b3fafffa3.jpg)

Missing texture here:
![20211031222538_1](https://user-images.githubusercontent.com/42658874/139726442-2dd85d00-4835-4de4-b546-a33a9894f547.jpg)

Not sure what these lines in the sky are supposed to be, visleafs or something maybe?
![20211031222619_1](https://user-images.githubusercontent.com/42658874/139726564-43cc8e47-de8c-461a-a5ac-43997d690e80.jpg)

Why is the helicopter rope transparent?
![20211031222823_1](https://user-images.githubusercontent.com/42658874/139726687-09d6e614-ba6c-4de5-8546-e993ccb2f8da.jpg)

====nmo_boardwalk====

Missing texture here:
![20211031223529_1](https://user-images.githubusercontent.com/42658874/139726630-cecddaa5-ed75-4d96-88a7-e3d537a30f82.jpg)

Why are these parts of the railing missing? There's just an invisible wall there instead:
![20211031223641_1](https://user-images.githubusercontent.com/42658874/139726792-c5a2e88e-1962-4711-8ed1-5f449bc758aa.jpg)

![20211031223646_1](https://user-images.githubusercontent.com/42658874/139726805-0cbc0513-22f9-45f2-88a7-79f145cd2c5b.jpg)

![20211031223651_1](https://user-images.githubusercontent.com/42658874/139726818-f9584a06-c64f-40a2-b649-237561ab9be0.jpg)

Why is the helicopter rope transparent?
![20211031223821_1](https://user-images.githubusercontent.com/42658874/139726855-ccd6a651-3f13-4ce3-bccb-3d7e7c84d4d5.jpg)

**Comment by felis-catus** [comment] 2021-11-01 19:06
These issues appear to be caused by add-ons, disable them first.

**Comment by TheUnstableNutcase** [comment] 2021-11-01 19:12
I'll test it right now and see if they persist

**Comment by TheUnstableNutcase** [comment] 2021-11-01 19:23
Just disabled all add-ons and restarted the game, and all the same issues appear to still be there. Not only that, but I also have a few new ones to add as well:

Not sure why this ghostly hologram of a welder is here, but whether it's intentional or not, this definitely makes the level look worse, and also can ruin immersion:
![20211101131322_1](https://user-images.githubusercontent.com/42658874/139728812-fca62e26-8377-42b5-8db8-4dac650d6bee.jpg)

![20211101131325_1](https://user-images.githubusercontent.com/42658874/139728846-8511753d-aa1d-4127-a549-ac6a388baa44.jpg)

Why is this lock blue before you weld it off?
![20211101131341_1](https://user-images.githubusercontent.com/42658874/139728904-e64d8ff7-4edb-4722-9816-7e2049ea3fc9.jpg)

![20211101131348_1](https://user-images.githubusercontent.com/42658874/139728922-fd6b407b-02ab-4364-8f76-e56541320482.jpg)

These board particles on nmo_rockpit are also broken:
![20211101131821_1](https://user-images.githubusercontent.com/42658874/139729005-2395531d-1f5c-411f-a61c-4b72f46d0da9.jpg)

**Comment by TheUnstableNutcase** [comment] 2021-11-01 20:01
Just verified the game files, same issues still persist

Not only that but I also seem to be getting some missing texture stuff on other maps too:
![20211101132925_1](https://user-images.githubusercontent.com/42658874/139733809-59596636-cad0-4f63-8f1a-c6c64f1059c7.jpg)

![20211101132951_1](https://user-images.githubusercontent.com/42658874/139733892-b720ca38-3e3d-4d00-8403-98b04183dc98.jpg)

![20211101132955_1](https://user-images.githubusercontent.com/42658874/139733909-baaf181b-0437-4676-85f1-cf36dbd819aa.jpg)

**Comment by felis-catus** [comment] 2021-11-01 21:54
Re: Missing textures and particles, unable to repro, and haven't seen or heard anyone else encountering this problem. Most likely a configuration issue on your end, reset video options with launch option `-autoconfig` and see if it persists.

**Comment by TheUnstableNutcase** [comment] 2021-11-02 02:44
> Re: Missing textures and particles, unable to repro, and haven't seen or heard anyone else encountering this problem. Most likely a configuration issue on your end, reset video options with launch option `-autoconfig` and see if it persists.

Tried launching with -autoconfig, it still persists

**Comment by AtheistNMRiH** [comment] 2021-11-03 07:41
> Players are expected to carry this gas can through this insanely dark tunnel, however if they have to carry an objective item, they can't use a flashlight or a lighter, so how are they even supposed to see? Zombies would be impossible to spot here. This area needs to be brightened up:

this is coop game so you must have a teammate with a flashlight, I think it is fine to have such dark spot of the map

> Why are these parts of the railing missing? There's just an invisible wall there instead:

there are fish nets which zombies "use" to climb, I guess that's why you shouldn't go there

**Comment by TheUnstableNutcase** [comment] 2021-11-03 07:51
> > Players are expected to carry this gas can through this insanely dark tunnel, however if they have to carry an objective item, they can't use a flashlight or a lighter, so how are they even supposed to see? Zombies would be impossible to spot here. This area needs to be brightened up:
> 
> this is coop game so you must have a teammate with a flashlight, I think it is fine to have such dark spot on the map
> 
> > Why are these parts of the railing missing? There's just an invisible wall there instead:
> 
> there are fish nets which zombies "use" to climb, I guess that's why you shouldn't go there

It’s one thing for an area of a map to be harder solo, but it’s another thing for an area to be borderline impossible solo. I think this dark tunnel is just completely unfair

**Comment by AtheistNMRiH** [comment] 2021-11-03 08:01
well, it is up to mapper then, but my opinion is that maps shouldn't be tweaked to make it possible to complete solo, I played that map today, all my teammates died, I had low health and I just made suicide before that section so we could complete it together again and we've completed it 🥳

**Comment by Holycrapjimhox** [comment] 2021-11-03 15:13
It's not impossible solo, it just takes a bit more time. If you wait a while outside the tunnel you will lure out all the runners outside where it's safe to kill them and while you do that, most shamblers will also walk out of the tunnel. It will be practically empty if you wait long enough, making it safe to enter with the gas can. Also, if there are still a couple of shamblers inside, you can hear their footsteps and avoid them easily since the tunnel is very wide.

**Comment by felis-catus** [comment] 2021-11-16 15:52
I'm closing this issue. Most of the problems reported in this thread are issues with your game (missing textures, broken particles), personal opinions on design of the maps, or insignificant such as "bad grammar on text" - I would like to remind that this is mainly an _issue_ tracker - feedback on the maps can be left in Steam discussions and Discord chat. Thanks for contributing!

**Closed by felis-catus** 2021-11-16 15:52 UTC
Labels: Status: Reviewed, Type: Map, Priority: Minimal
