### ISSUE TITLE
not getting hit by zombies 

### ISSUE THREAD

**Issue by theghost2333** [nmrih/source-game#274] opened 2013-08-03 13:05 UTC
![2013-08-03_00053](https://f.cloud.github.com/assets/5095321/905610/532c4ad6-fc3d-11e2-97cb-f6379184f4ff.jpg)

**Comment by Fersigal** [comment] 2018-01-18 17:45
Title: not getting hit by zombies -> nmo_chinatown zombie grabbing glitch
Bug appears with most prop_dynamic (if this is prop_dynamic indeed), other example would be the rotating door on Broadway at start (metal fence) or the fact that you can get hit / get damage from standing onto tables on Cabin eventhough the zombie is at the other side.

**Comment by Bubka3** [comment] 2018-02-16 21:55
**Duplicate Closure**
This issue has been closed because it has already been reported under a previous issue ID.
Please follow the issue below for further updates.

Duplicate of #223

**Closed by Bubka3** 2018-02-16 21:55 UTC
Labels: code, reviewed
