### ISSUE TITLE
[public 1.10.0] Third person character models do not point the flashlight straight

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#1095] opened 2019-11-19 03:08 UTC
![flashlight](https://user-images.githubusercontent.com/35630284/69113016-8bfd6880-0a60-11ea-9bd4-520b9e4c50d6.jpg)
When a player holds a one-handed melee weapon and equips a flashlight using the F key, the first person model will show the flashlight pointing directly in front of the player, while the third person model will show the flashlight pointing at the ground. This prevents said player from lighting up corridors for their teammates, they are forced to switch to a one handed firearm (beretta, Glock 17, Ruger) or to the flashlight itself. This allows the character model to shine the flashlight straight in front of it.

**Comment by Winning117** [comment] 2020-02-08 23:15
Duplicate of https://github.com/nmrih/source-game/issues/526

**Comment by Holycrapjimhox** [comment] 2020-02-08 23:34
It's easier to leave the older entry closed because this post has a bit more detail and already has the tags.

**Comment by felis-catus** [comment] 2022-06-07 15:35
Fixed in dev-r9523.

**Closed by felis-catus** 2022-06-07 15:35 UTC
Labels: Status: Reviewed, Type: Assets, Priority: Minimal
