### ISSUE TITLE
Out of ammo handguns M1911, Luger and Beretta prime forward when sprinting.

### ISSUE THREAD

**Issue by RoyRoyMcBoii** [nmrih/source-game#347] opened 2013-08-15 09:12 UTC
Version 1.06 and 1.07
What happens
This is a very minor bug which just bugs me ever so slightly, it's not gamebreaking, however it is a bug.  When the M1911, Luger or Beretta pistols are out of ammunition in their clip, the sprinting animation shows the gun primed forward for a moment and then primes back.  I hope this isn't a duplicate post, I did look in Minor Bugs and I didn't find anything in regards to it.

When does it happen?
When sprinting with M1911, Luger or Beretta pistols that have no ammo, any map, any gamemode.

Steps to reproduce the issue (How did you do it?)
Step. 1:  Get a M1911, Luger or Beretta pistol.  
Step 2. Waste the clip (preferably on zombies)
Step 3. Sprint and look at the gun prime forward

**Comment by Winning117** [comment] 2018-03-31 09:19
Duplicate of [#59](https://github.com/nmrih/source-game/issues/59), needs to be closed.

**Closed** 2018-03-31 10:05 UTC
