### ISSUE TITLE
[Issue] Hammer Ammo Check

### ISSUE THREAD

**Issue by iVoxiom** [nmrih/source-game#1383] opened 2022-11-22 22:19 UTC
When holding R to check how many boards the player has, the voice line will say 'round' instead of 'board.'

For example, if the player has a board and holds R, the character will say, '1 round left.'

**Comment by felis-catus** [comment] 2022-11-22 22:22
Duplicate of #1356

**Closed by felis-catus** 2022-11-22 22:22 UTC
