### ISSUE TITLE
Voice bug while playing as "badass" twelve rounds left

### ISSUE THREAD

**Issue by tazebama** [nmrih/source-game#816] opened 2017-02-21 16:09 UTC
when i use a 9mm gun ,, and i reach 12 rounds ,, then i hold R to see the ammo ,, i hear her says :
twelve rounds left but then it repeats it without stopping unless the round ends
twelve rounds left .... twelve rounds left .... twelve rounds left..... etc
i am not sure on what kind of 9mm does this bug triggers ,, but last time it happened when i used the half green 9mm gun
,,
i don't think posting my system info is important ,,, but here u go
CPU : core 2 duo e8200
GPU : nvidia gt 610 2gb
RAM : 4 gb

**Comment by Bubka3** [comment] 2018-01-13 05:42
Duplicate of #631 
See that issue for all future updates.

**Closed by Bubka3** 2018-01-13 05:42 UTC
Labels: code, duplicate, reviewed
