### ISSUE TITLE
[public-1.12.3] nmo_fema electrified puddle sound playing throughout other parts of the map

### ISSUE THREAD

**Issue by TheUnstableNutcase** [nmrih/source-game#1349] opened 2022-09-30 03:25 UTC
I got to the surface section towards the end of nmo_fema and I could still hear a constant electricity noise playing the whole time at what sounded like relatively high/full volume. As far as I can remember I don't think I've experienced this before

**Comment by AtheistNMRiH** [comment] 2022-09-30 03:36
could that sound come from some zombie\zombie's corpse? I got many times that bug with other looped sounds (fire, electricity)

**Comment by AtheistNMRiH** [comment] 2022-10-15 14:27
I can't reproduce that bug

**Comment by felis-catus** [comment] 2022-10-16 13:01
Closing as it's not an issue with the map.

**Closed by felis-catus** 2022-10-16 13:01 UTC
Labels: Status: Reviewed, Type: Map, Priority: Minimal
