### ISSUE TITLE
[public-1.13.0] A point that can get you stuck on nmo_asylum

### ISSUE THREAD

**Issue by Klowby** [nmrih/source-game#1364] opened 2022-11-03 11:03 UTC
Accidently landed on this audio, which is pointed by the red arrow in the picture below.
Then I got stuck.
![picture](https://user-images.githubusercontent.com/42507880/199702660-e7f3b222-23d4-4444-ac35-afe517fd4fcd.png)

How to reproduce:
Standing on that audio, then jump, you will get stuck after landing.

Not sure it only happens to me or not, also not sure whether it has already been found... I'd better just report it.

**Comment by felis-catus** [comment] 2022-11-03 11:05
Duplicate of #1360

**Closed by felis-catus** 2022-11-03 11:05 UTC

**Comment by Klowby** [comment] 2022-11-03 11:09
Sorry for not paying attention to check discord messages and close issues.
