### ISSUE TITLE
[public-1.12.3] Sprint reload

### ISSUE THREAD

**Issue by Plazehorta** [nmrih/source-game#1357] opened 2022-10-23 09:52 UTC
By tapping R while sprinting your movement speed would return to walking while exiting the sprinting animation. But if you keep holding down W+shift in the whole process you will start sprinting when the reload animation starts.

"Fixing" it will probably ruin this game for everyone.

**Comment by dysphie** [comment] 2022-10-23 15:03
Duplicate of #390

**Closed** 2022-10-23 15:03 UTC
