### ISSUE TITLE
[public-1.11.5] Autojoin causes wrong view height

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1208] opened 2021-09-01 16:09 UTC
cl_skip_joingame_dialog 1 sometimes causes players to spawn with a lower view height that flickers to normal height. This is fixed by ducking

**Comment by felis-catus** [comment] 2022-02-20 15:22
For reference, this issue is caused by `ds_autorecord 1`.

**Comment by felis-catus** [comment] 2022-06-07 02:55
Fixed in src-r6348.

**Closed by felis-catus** 2022-06-07 02:55 UTC
Labels: Status: Reviewed, Type: Code, Priority: Minimal
