### ISSUE TITLE
Some zombies love heal crates.

### ISSUE THREAD

**Issue by ghost** [nmrih/source-game#358] opened 2013-08-17 18:00 UTC
Some zombies get stuck in the healing crates.
![2013-08-17_00001](https://f.cloud.github.com/assets/5167329/981483/b7f10874-0766-11e3-9f86-6c062685108c.jpg)
![2013-08-17_00002](https://f.cloud.github.com/assets/5167329/981484/b961789c-0766-11e3-8325-23a5c36b9e37.jpg)
![2013-08-17_00003](https://f.cloud.github.com/assets/5167329/981485/baba781a-0766-11e3-8c65-56baa50bcd02.jpg)
![2013-08-17_00004](https://f.cloud.github.com/assets/5167329/981487/bc255332-0766-11e3-8c2d-b8391d09f4ae.jpg)
![2013-08-17_00005](https://f.cloud.github.com/assets/5167329/981488/bd9c51de-0766-11e3-9787-3ef4ce3ae787.jpg)
![2013-08-17_00006](https://f.cloud.github.com/assets/5167329/981489/bf148d10-0766-11e3-850f-2cd6c29bc7ad.jpg)
![2013-08-17_00007](https://f.cloud.github.com/assets/5167329/981490/c0561004-0766-11e3-8d69-d0629cf77f1a.jpg)
![2013-08-17_00008](https://f.cloud.github.com/assets/5167329/981491/c20912a2-0766-11e3-860f-cc76faed1197.jpg)
![2013-08-17_00009](https://f.cloud.github.com/assets/5167329/981492/c36da73e-0766-11e3-8728-245f82720a60.jpg)
![2013-08-17_00010](https://f.cloud.github.com/assets/5167329/981493/c4c3f43a-0766-11e3-85b6-0ebdb8f64d23.jpg)
![2013-08-17_00011](https://f.cloud.github.com/assets/5167329/981494/c618fb0a-0766-11e3-9d3a-9ba7e13f6f66.jpg)
![2013-08-17_00012](https://f.cloud.github.com/assets/5167329/981495/c79131a0-0766-11e3-8595-4c3e1b605ce8.jpg)

**Comment by felis-catus** [comment] 2018-03-13 17:04
Fixed in src-r4328.

**Comment by Winning117** [comment] 2018-03-14 03:44
Wait you actually fixed this issue? I never thought I'd see the day. Praise Felis <3

**Comment by Winning117** [comment] 2018-03-26 09:20
Not completed, needs to be reopened because I found a way to break it again in src-r4367/dev-r8757. https://www.youtube.com/watch?v=Kry2Do5l3gA

**Comment by Winning117** [comment] 2018-04-04 06:39
Confirmed fixed in src-r4388/dev-r8772, needs to be closed.

**Comment by felis-catus** [comment] 2018-04-04 06:43
In addition, this issue was fixed for real in commit src-4374.

**Closed by felis-catus** 2018-04-04 06:43 UTC
Labels: Priority: Normal, Status: Completed, Type: Code
