### ISSUE TITLE
Toxteth Broke, update 1.11

### ISSUE THREAD

**Issue by saintsfan3324** [nmrih/source-game#1120] opened 2020-03-05 07:30 UTC
daytime nmo_toxteth is currently broken, unsure about night version
1. fuel tank to blow up graveyard wall doesnt spawn
![224260_20200305002332_1](https://user-images.githubusercontent.com/61821188/75957617-9dd01380-5e77-11ea-8998-27784a759fe9.png)
2. clipping broken on certain surfaces, such as this gate opposite to the door you need to open with the crank in the sewers 
![224260_20200305001350_1](https://user-images.githubusercontent.com/61821188/75957763-f2738e80-5e77-11ea-89c4-3a7f6e7e92e2.png)
3. crank fails to spawn in the sewers 
![224260_20200305002744_1](https://user-images.githubusercontent.com/61821188/75957969-762d7b00-5e78-11ea-9188-498f2d86234c.png)
possible many more broken bugs, unsure as i am unable to progress thru the map
pls fix

**Comment by dysphie** [comment] 2020-03-05 07:56
I can't seem to reproduce any of these in singleplayer.  The gate is solid and both the fuel tank and crank seem to spawn just fine (multiple locations)

**Comment by AtheistNMRiH** [comment] 2020-03-07 11:17
I also don't see any problem
![nmo_toxteth0000](https://user-images.githubusercontent.com/11333747/76142383-c6d2ed00-609f-11ea-8f30-7c037005f0c4.jpg)

**Comment by felis-catus** [comment] 2020-03-08 09:07
Unable to reproduce as well, this might have been a temporary problem with the server. (faulty plugin etc.)

**Comment by felis-catus** [comment] 2020-03-10 14:05
Closing, if these issues resurface create new specific threads for them.

**Closed by felis-catus** 2020-03-10 14:05 UTC
Labels: Priority: Normal, Status: Reviewed, Type: Map
