### ISSUE TITLE
 Big bug with new physics

### ISSUE THREAD

**Issue by Pla33** [nmrih/source-game#1152] opened 2020-07-11 18:41 UTC
When located on certain entities, zombies do not touch the player, which greatly affects the gameplay of many maps, including official ones. Players very often use these bugs, which is why map ideas lose their meaning.
Bugs work on: Doors, platforms, elevators, objects, weapons, boxes, barrels.
Examples:

(official map) -

nmo_fema (door and platform):

![20200711213439_1](https://user-images.githubusercontent.com/42173955/87230373-2aac5000-c3c9-11ea-8606-0f93fd8d2b61.jpg)
![20200711213448_1](https://user-images.githubusercontent.com/42173955/87230386-3bf55c80-c3c9-11ea-8ab1-d5a9e870ea04.jpg)
![20200711213613_1](https://user-images.githubusercontent.com/42173955/87230394-4c0d3c00-c3c9-11ea-80b7-88f479e38f23.jpg)
![20200711213616_1](https://user-images.githubusercontent.com/42173955/87230397-4fa0c300-c3c9-11ea-8566-b0a99f69249a.jpg)
![20200711213634_1](https://user-images.githubusercontent.com/42173955/87230404-5af3ee80-c3c9-11ea-8b1f-0b0b02ffd932.jpg)
![20200711213626_1](https://user-images.githubusercontent.com/42173955/87230408-5e877580-c3c9-11ea-820f-0af2f460f136.jpg)
![20200711213702_1](https://user-images.githubusercontent.com/42173955/87230412-6cd59180-c3c9-11ea-9884-216e593f40fc.jpg)

nmo_brooklyn (elevator):

![20200711220514_1](https://user-images.githubusercontent.com/42173955/87230440-98f11280-c3c9-11ea-95a5-bf75584e546e.jpg)
![20200711220907_1](https://user-images.githubusercontent.com/42173955/87230449-a27a7a80-c3c9-11ea-959a-5bdf2b7cd0e8.jpg)
![20200711220911_1](https://user-images.githubusercontent.com/42173955/87230454-a73f2e80-c3c9-11ea-8b13-b50f60b57f89.jpg)

nmo_broadway (train):

![20200711223406_1](https://user-images.githubusercontent.com/42173955/87230474-c1790c80-c3c9-11ea-9adc-e3a420178a05.jpg)
![20200711223417_1](https://user-images.githubusercontent.com/42173955/87230480-c8078400-c3c9-11ea-952f-f90a38832d15.jpg)

nmo_underground (elevator):

![20200711231542_1](https://user-images.githubusercontent.com/42173955/87230501-f6855f00-c3c9-11ea-8317-fca23bee21a9.jpg)
![20200711231514_1](https://user-images.githubusercontent.com/42173955/87230506-fc7b4000-c3c9-11ea-98b4-edd274115939.jpg)
![20200711231507_1](https://user-images.githubusercontent.com/42173955/87230509-02712100-c3ca-11ea-97c6-f19b43ad19e3.jpg)
![20200711231341_1](https://user-images.githubusercontent.com/42173955/87230512-08670200-c3ca-11ea-81e9-b347710027de.jpg)
![20200711231402_1](https://user-images.githubusercontent.com/42173955/87230542-4e23ca80-c3ca-11ea-8787-5563c3d388f2.jpg)

nmo_shelter (An example of how to get around any defense on any map.):

![20200711230805_1](https://user-images.githubusercontent.com/42173955/87230552-609e0400-c3ca-11ea-81a4-acee24b25170.jpg)
![20200711230802_1](https://user-images.githubusercontent.com/42173955/87230562-6e538980-c3ca-11ea-9ff8-10b0a50a72ad.jpg)
![20200711230757_1](https://user-images.githubusercontent.com/42173955/87230570-73183d80-c3ca-11ea-900a-1306b64da760.jpg)
![20200711230754_1](https://user-images.githubusercontent.com/42173955/87230653-defaa600-c3ca-11ea-9924-c2d1620d7f1c.jpg)

not official -

nmo_miner_detour_v3 (elevator):

![20200711225655_1](https://user-images.githubusercontent.com/42173955/87231032-369a1100-c3cd-11ea-9fdb-27dfe7514942.jpg)
![20200711225650_1](https://user-images.githubusercontent.com/42173955/87231034-38fc6b00-c3cd-11ea-9b97-e9ffbd381828.jpg)
![20200711225659_1](https://user-images.githubusercontent.com/42173955/87231036-3dc11f00-c3cd-11ea-9bae-92bbadd7ec3b.jpg)
![20200711225706_1](https://user-images.githubusercontent.com/42173955/87231039-41ed3c80-c3cd-11ea-8dc6-56270ee2c559.jpg)

nmo_line_v2_y9v16 (platform):

![20200711224933_1](https://user-images.githubusercontent.com/42173955/87231095-ab6d4b00-c3cd-11ea-973a-88a9a713163f.jpg)
![20200711224938_1](https://user-images.githubusercontent.com/42173955/87231098-b58f4980-c3cd-11ea-8ec9-a4eee57990e1.jpg)
![20200711224942_1](https://user-images.githubusercontent.com/42173955/87231103-be801b00-c3cd-11ea-9b81-3000d5916522.jpg)

nmo_cold_black_y9v4 (elevator):
![20200711223808_1](https://user-images.githubusercontent.com/42173955/87231154-26366600-c3ce-11ea-8869-dbbbd0fbfe9c.jpg)
![20200711223801_1](https://user-images.githubusercontent.com/42173955/87231159-2a628380-c3ce-11ea-8018-5e81f2d52631.jpg)
![20200711223809_1](https://user-images.githubusercontent.com/42173955/87231150-20d91b80-c3ce-11ea-9979-b1aa56d1ea2f.jpg)

(Zombies do not touch portable boxes and barrels. On any map where there are boxes, players block zombies. This greatly affects the gameplay and all the ideas of the author lose their meaning!):

nmo_medical_clinic_lite_v2 (boxes):

![20200711225326_2](https://user-images.githubusercontent.com/42173955/87230986-c9867b80-c3cc-11ea-84bf-c7f7cefc3940.jpg)

nmo_mansion_v1_rus (boxes):

![20200711225214_1](https://user-images.githubusercontent.com/42173955/87231006-f175df00-c3cc-11ea-8cbc-f24ee70da1d2.jpg)
![20200711225204_1](https://user-images.githubusercontent.com/42173955/87231007-f63a9300-c3cc-11ea-9bfc-fba50fb813ed.jpg)
PS - All these errors are associated with the new physics of the game. Therefore, I did not do several posts on the same bug.

**Comment by Holycrapjimhox** [comment] 2020-07-11 19:37
Duplicate of #1143

**Comment by Pla33** [comment] 2020-07-11 19:51
This is not a duplicate. I expanded the information about the bug. The developers did not understand the meaning of this bug. Therefore, I sent it to the extended information

**Comment by Holycrapjimhox** [comment] 2020-07-11 19:54
Yes it is a duplicate because it's the same issue. This is the way bugs are tracked in this github repository. The extra information is appreciated though, that's why I referenced the original report. A link to this post has been added to it.

**Comment by Pla33** [comment] 2020-07-11 20:02
This is a very serious mistake. The scale and impact on the players is enormous. Many people use these errors and even think that it is so conceived. The idea of ​​the author in a certain place loses its meaning. I supplemented the information about this error. Because players kill the idea of ​​the author and defend themselves on the map, standing still, doing nothing.

**Comment by Holycrapjimhox** [comment] 2020-07-11 20:16
No need to over exaggerate the problem. This issue has been known for a while and I've only seen a minority of players using it to their advantage, and even then they are missing the point of the game if they go to such lengths to simplify the combat in such a stupid way. Nobody in their right mind thinks this is an intentional mechanic. However, I do agree that it's cheap and it can affect gameplay for others if the person doing it manages to take out all of the runners in a difficult map for example. The issue has been effectively reported, the devs will eventually take a look at it and try to fix it.

**Comment by felis-catus** [comment] 2020-07-12 06:41
Duplicate of #1143. You can repost images and continue discussion in the linked issue.

**Closed by felis-catus** 2020-07-12 06:41 UTC
