### ISSUE TITLE
Nmo_Fema Electric Box Bug!

### ISSUE THREAD

**Issue by Wazanator** [nmrih/source-game#726] opened 2015-04-24 03:26 UTC
Sometimes you can't shoot electric box to cut power to electrified puddle.

https://www.youtube.com/watch?v=EVZQLaigNT0

http://steamcommunity.com/app/224260/discussions/3/618459405727404302/

**Comment by AtheistNMRiH** [comment] 2018-01-21 06:34
I guess it is same as #743

**Comment by Bubka3** [comment] 2018-01-22 20:56
Marking as duplicate of #743 

Follow that issue for all further updates.

**Closed by Bubka3** 2018-01-22 20:56 UTC
Labels: duplicate, map, reviewed
