### ISSUE TITLE
High Jump by Walkie-talkie

### ISSUE THREAD

**Issue by yomox9** [nmrih/source-game#805] opened 2016-06-27 12:23 UTC
Version : NMRiH 1.09.6
What happens : High Jump by Walkie-talkie
When does it happen : Player can high jump
Steps to reproduce the issue (How did you do it?) : Drop Walkie-talkie and Jump ( keep press 1 key and w key, and then press space key)
Youtube
[Complete nmo_l4d_the_sacrifice_v1 in 5.5 minutes or less](https://www.youtube.com/watch?v=-wqMA-lzvwo)

**Comment by Bubka3** [comment] 2018-01-14 16:52
Prop surfing is a source engine feature.

**Comment by Bubka3** [comment] 2018-01-23 00:40
A community plugin fixes this by setting the solid flags:

```sourcepawn
public void OnEntityCreated(int entity, const char[] classname)
{
	if(!GetConVarBool(IsPluginEnabled)) 
		return;

	if(StrEqual(classname, "item_walkietalkie"))	
	{
		SetEntProp(entity, Prop_Send, "m_usSolidFlags", 8);
	}
}
```

**Comment by Fersigal** [comment] 2018-01-23 10:42
This happens, because i slightly suspect that this is related to what the pills boosting used to be and that when you drop it, it registers as if it were a prop_physics, so you have a chance that it boosts you in the air, only works on multiplayer though. It's very inconsistent on singleplayer and very hard to produce. But when you're playing with others on a server it's random and sometimes it would launch you 6 gordons in the air or othertimes it wouldn't launch you at all and would give you a slight boost.

**Comment by Holycrapjimhox** [comment] 2018-01-23 17:03
I think the height is dependent on the angle your camera is at when you look up. Also, I believe you do not have to play with others to reproduce it, you just need to play on a server where your ping is 20 or more. What I mean is that you need a bit of latency to pull it off, that's why it can't be reproduced in a listen server.

**Comment by MintyDysphie** [comment] 2018-01-24 02:06
I came up with that plugin and I wouldn't recommend it. Setting `m_usSolidFlags` to `8` to match that of other items prevents boosting but causes shaky models in client-side thirdperson. I'm currently rewriting it to use `CBaseEntity::ShouldCollide` instead.

**Comment by Winning117** [comment] 2018-02-02 02:13
Just adding that it can be pulled off with 1ms ping (https://www.youtube.com/watch?v=hZaZXW-YGds). If you aren't host then the higher your ping, the higher you launch.

**Comment by MintyDysphie** [comment] 2018-02-02 15:00
Current plugin setup, not the preferable approach:

```#define COLLISION_GROUP_DEBRIS 1

public void OnEntityCreated(int entity, const char[] classname)
{
	if (StrEqual(classname, "item_walkietalkie"))
	{
		SDKHook(entity, SDKHook_ThinkPost, Hook_WalkieFix);
	}
}

public void Hook_WalkieFix(int walkie)
{
	SetEntProp(walkie, Prop_Send, "m_CollisionGroup", COLLISION_GROUP_DEBRIS);
}```
public void OnEntityCreated(int entity, const char[] classname)
{
	if (StrEqual(classname, "item_walkietalkie"))
	{
		SDKHook(entity, SDKHook_ThinkPost, Hook_WalkieFix);
	}
}

public void Hook_WalkieFix(int walkie)
{
	SetEntProp(walkie, Prop_Send, "m_CollisionGroup", COLLISION_GROUP_DEBRIS);
}```

**Comment by Bubka3** [comment] 2018-02-02 21:32
Felis already applied a fix for this in the dev build. Its just hes not sure if he fixed it or if he simply cant do the jump LOL.

**Comment by Fersigal** [comment] 2018-02-02 22:10
all i can say: git gud

**Comment by felis-catus** [comment] 2018-02-02 22:50
Got gud and confirmed the fix, couldn't pull it off anymore. Marking this as resolved.

**Comment by Bubka3** [comment] 2018-02-17 17:32
**Resolved Closure**
This issue has been closed as it has been resolved in the current dev build.
It will be available to the public in the next steam release. Thanks for reporting!

Additional comments: tested bins r8726

**Closed by Bubka3** 2018-02-17 17:32 UTC
Labels: code, resolved, reviewed
