### ISSUE TITLE
Zombie melee swing can hurt players standing behind the zombie

### ISSUE THREAD

**Issue by Ryan-nmrih** [nmrih/source-game#972] opened 2018-05-07 23:05 UTC
Players will take damage from zombies who have their back to the player if the player is close enough. This happens in both the public and dev build.

https://streamable.com/hr0tl
https://streamable.com/nihy5

**Comment by Holycrapjimhox** [comment] 2022-02-19 19:36
Reported again here with more info and videos: https://github.com/nmrih/source-game/issues/1288
This entry should be closed to avoid confusion.

**Comment by felis-catus** [comment] 2022-02-19 20:10
Duplicate of #1288

**Closed by felis-catus** 2022-02-19 20:10 UTC
Labels: Status: Reviewed, Type: Code, Priority: Minimal
