### ISSUE TITLE
nmo_zephyr (map bugs)

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#846] opened 2018-01-27 17:04 UTC
**• Item softlocks**

1) Ways to bug the gascan/welder:
![20180127111419_1](https://user-images.githubusercontent.com/35630284/35474043-ac7f58fe-0367-11e8-82d9-b15cc3065faa.jpg)
![20180127111425_1](https://user-images.githubusercontent.com/35630284/35474044-aca406a4-0367-11e8-824c-db296b40693a.jpg)
![20180127111445_1](https://user-images.githubusercontent.com/35630284/35474045-acc8aa0e-0367-11e8-9a1b-9c6566547a1f.jpg)
![20180127111524_1](https://user-images.githubusercontent.com/35630284/35474046-aceb5dc4-0367-11e8-8221-727b92dbb471.jpg)
![20180127111603_1](https://user-images.githubusercontent.com/35630284/35474047-ad0d38b8-0367-11e8-9214-94200d08aef5.jpg)
(I couldn't bug the welder behind the bushes, but it's technically possible to throw it far away, I'd suggest correctly clipping the bushes area)
![20180127111735_1](https://user-images.githubusercontent.com/35630284/35474048-ad2defea-0367-11e8-87ad-a0762dc73efd.jpg)
![20180127111744_1](https://user-images.githubusercontent.com/35630284/35474049-ad50680e-0367-11e8-80fc-b65592a95887.jpg)
![20180127111755_1](https://user-images.githubusercontent.com/35630284/35474050-ad700f6a-0367-11e8-9447-98c3049d3895.jpg)
![20180127111758_1](https://user-images.githubusercontent.com/35630284/35474051-ad91894c-0367-11e8-94f5-63ed41848559.jpg)
![20180127111807_1](https://user-images.githubusercontent.com/35630284/35474052-adb3bb02-0367-11e8-9865-294fc29a4832.jpg)
![20180127111813_1](https://user-images.githubusercontent.com/35630284/35474053-add91140-0367-11e8-8af9-2a5bfa3dd383.jpg)
(If there's a welder, you can get the gas can out, but if not, then it's a softlock)
![20180127111830_1](https://user-images.githubusercontent.com/35630284/35474054-ae03fe82-0367-11e8-9db9-7f41e58c2423.jpg)
![20180127111835_1](https://user-images.githubusercontent.com/35630284/35474055-ae26da38-0367-11e8-8f94-5879d8a28c2f.jpg)
![20180127111853_1](https://user-images.githubusercontent.com/35630284/35474056-ae4bb844-0367-11e8-98b1-d72018c5482f.jpg)
![20180127111912_1](https://user-images.githubusercontent.com/35630284/35474057-ae6b1176-0367-11e8-803f-c8f6d36a4bb3.jpg)
![20180127112000_1](https://user-images.githubusercontent.com/35630284/35474058-aeb91f9c-0367-11e8-871d-b896f7ba9d0a.jpg)
![20180127112022_1](https://user-images.githubusercontent.com/35630284/35474059-aedc714a-0367-11e8-8d18-0fad70316091.jpg)
![20180127112037_1](https://user-images.githubusercontent.com/35630284/35474060-af019ac4-0367-11e8-9360-556f9475b5c5.jpg)
![20180127112039_1](https://user-images.githubusercontent.com/35630284/35474061-af247bc0-0367-11e8-871c-b56e70724829.jpg)
![20180127112113_1](https://user-images.githubusercontent.com/35630284/35474062-af44f5d0-0367-11e8-8157-75e2204d2d22.jpg)
![20180127112139_1](https://user-images.githubusercontent.com/35630284/35474063-af65c63e-0367-11e8-8ab9-b4a69ec47bed.jpg)
![20180127112221_1](https://user-images.githubusercontent.com/35630284/35474064-af84ff40-0367-11e8-9e03-295668a81b43.jpg)
![20180127112430_1](https://user-images.githubusercontent.com/35630284/35474065-afa8bed0-0367-11e8-9dff-0fdc64ca1186.jpg)
![20180127112538_1](https://user-images.githubusercontent.com/35630284/35474066-afc816d6-0367-11e8-99b2-3f2480499eac.jpg)

2) Ways to bug the FUBAR objective item:
![20180127113550_1](https://user-images.githubusercontent.com/35630284/35474074-e062f018-0367-11e8-8763-23f06ee51c98.jpg)
![20180127113626_1](https://user-images.githubusercontent.com/35630284/35474075-e084b5ae-0367-11e8-8dbd-f57a2d772e52.jpg)
![20180127113704_1](https://user-images.githubusercontent.com/35630284/35474076-e0ac2396-0367-11e8-96ef-78c7d5fa5891.jpg)
![20180127113717_1](https://user-images.githubusercontent.com/35630284/35474077-e0d87360-0367-11e8-99c6-ffc9cb6cf560.jpg)
![20180127113728_1](https://user-images.githubusercontent.com/35630284/35474078-e0feca2e-0367-11e8-8e0b-602bcf5753a4.jpg)
![20180127113824_1](https://user-images.githubusercontent.com/35630284/35474079-e1209a3c-0367-11e8-83f5-82c843755fab.jpg)
![20180127113841_1](https://user-images.githubusercontent.com/35630284/35474080-e1513d9a-0367-11e8-9033-f5ee771331a6.jpg)

**• Other softlocks:**

1) Early code softlock:
If you enter the correct code in the keypad before the train engineer stops talking (after the objective to enter the code pops up) you'll softlock the map
![20180127111127_1](https://user-images.githubusercontent.com/35630284/35474156-1265d494-0369-11e8-89d1-a704d6d0f5dc.jpg)

2) Train blocking softlock Nº1:
If you ride the front of the train just after it exits the warehouse, you can get stuck in between the train and the end of the map, causing a softlock. The objective to hit the leaver won't appear unless the train reaches the end of the tracks, which becomes impossible when a player is in the middle.
![20180127110607_1](https://user-images.githubusercontent.com/35630284/35474183-90def152-0369-11e8-8c61-fac0c4c49f26.jpg)
![20180127110640_1](https://user-images.githubusercontent.com/35630284/35474184-91042dbe-0369-11e8-9cf7-bf60f6439fdc.jpg)
![20180127110645_1](https://user-images.githubusercontent.com/35630284/35474185-9124ac42-0369-11e8-8754-bde103b52177.jpg)

3) Train blocking softlock Nº2:
You can basically stop the train completely by standing in front of it or at the sides when it's making a turn. If the train does not reach its intended destination, objectives will not update, causing a softlock.
![20180127110715_1](https://user-images.githubusercontent.com/35630284/35474194-bf37b03e-0369-11e8-8655-2e78800c8a36.jpg)
![20180127110723_1](https://user-images.githubusercontent.com/35630284/35474195-bf5a9edc-0369-11e8-8b76-f1018ab133cb.jpg)

4) Turntable blocking:
You can block the movement of the turntable by standing on the metal block while touching the top of the turntable. That way, the train never moves.
![20180127140831_1](https://user-images.githubusercontent.com/35630284/35474296-fd03f458-036a-11e8-8077-beb0fa37ff1b.jpg)

**• Map oddities:**

1) You can see the skybox if you zombie boost on top of the stairs in spawn:
![20180127105435_1](https://user-images.githubusercontent.com/35630284/35474209-ed1fa498-0369-11e8-8997-d142210ac5ba.jpg)
![20180127105438_1](https://user-images.githubusercontent.com/35630284/35474210-ed445a7c-0369-11e8-9669-cf109a28ad67.jpg)

2) Bathroom door clips into the urinal:
![20180127105650_1](https://user-images.githubusercontent.com/35630284/35474218-fdb13bd2-0369-11e8-9355-3819cf856d6a.jpg)

3) Z-fighting on the elevator hand rails:
![20180127110251_1](https://user-images.githubusercontent.com/35630284/35474230-25a0f8da-036a-11e8-994b-57f1b0d509bc.jpg)
![20180127110255_1](https://user-images.githubusercontent.com/35630284/35474231-25c38b34-036a-11e8-949d-965ce8040d59.jpg)
![20180127111020_1](https://user-images.githubusercontent.com/35630284/35474232-25e47d8a-036a-11e8-872d-be7860c67dae.jpg)
![20180127111025_1](https://user-images.githubusercontent.com/35630284/35474234-260557d0-036a-11e8-8de2-41a41976184d.jpg)
![20180127111242_1](https://user-images.githubusercontent.com/35630284/35474235-262d86e2-036a-11e8-9023-78ff2a2aaea9.jpg)

4) A small gap between the elevator floor and the fences can crush players:
![20180127110301_1](https://user-images.githubusercontent.com/35630284/35474243-43cdbfa0-036a-11e8-8038-2f32383123e9.jpg)

**Comment by Fersigal** [comment] 2018-01-27 20:11
Keep them coming, i'm not really more into submitting map bugs, would be nice if you could do the new maps first though (nmo_broadway 2 and such)

**Comment by Holycrapjimhox** [comment] 2018-01-28 05:37
I've already reported many issues for broadway2 and suzhou. Broadway2 I think it's mostly fine, maybe a couple of changes that I proposed on the Complaints issue would be nice. Suzhou is almost completely done, except for the fact that the spawn/respawn of shamblers does not work properly. Spawn density is too low or non existant, and if they do spawn, they spawn late, so players are able to rush through the chokepoints without any effort. If Billion manages to fix said spawning issues, the map is basically complete. I've reported so many issues on suzhou that I'm having trouble finding new ones.

**Comment by AtheistNMRiH** [comment] 2018-04-10 14:11
confirmed fixed in r8784 (except blocking turntable, no idea how to fix that, probably same with train), needs to be closed

**Comment by Holycrapjimhox** [comment] 2018-04-10 18:00
This should not be closed until the turtable and train softlocks are fixed. Those are pretty severe. Unless there is no physical way to fix them, this should remain open.

**Comment by AtheistNMRiH** [comment] 2018-04-11 09:07
I guess it can be closed now since these bugs won't fix (according to discord)

**Closed** 2018-04-13 13:59 UTC
Labels: Status: Reviewed, Type: Map
