### ISSUE TITLE
Weird lighter console issue

### ISSUE THREAD

**Issue by Fersigal** [nmrih/source-game#855] opened 2018-02-09 12:10 UTC
Steps to reproduce:
1) Activate lighter
2) Dequip it
3) Wait
4) Profit
![20180209130920_1](https://user-images.githubusercontent.com/11538773/36027197-8779dfe2-0d9a-11e8-8a94-6a85237e2d2a.jpg)

**Comment by AtheistNMRiH** [comment] 2018-02-09 18:13
happens to most of the info_particle_system

**Comment by Winning117** [comment] 2018-04-05 05:01
Unable to reproduce in dev. Any more steps to reproduce this?

**Comment by Fersigal** [comment] 2018-04-05 07:49
Git gud
![image](https://user-images.githubusercontent.com/11538773/38353424-ae50a604-38b6-11e8-874d-f88a9b2c4e20.png)

**Comment by Winning117** [comment] 2018-04-05 07:51
What are your settings? Felis and I both tried to reproduce this and can't.

**Comment by DDysphie** [comment] 2018-04-05 07:52
The following demo triggers the error:
[lighter.zip](https://github.com/nmrih/source-game/files/1878976/lighter.zip)

**Comment by felis-catus** [comment] 2020-02-18 17:43
At worst this is annoying spew, it has no other repercussions. Closing.

**Closed by felis-catus** 2020-02-18 17:43 UTC
Labels: Priority: Minimal, Status: Assigned, Type: Code
