### ISSUE TITLE
[public-1.11.3] nmrih_extract_preview can't be parented to other entities (rope is missing on nmo_boardwalk)

### ISSUE THREAD

**Issue by TheUnstableNutcase** [nmrih/source-game#1169] opened 2021-01-24 01:46 UTC
When the helicopter arrives on nmo_boardwalk, the rope to the helicopter is invisible. Don't know if this happens all the time or not and I also don't know if this happens to all players or not. Several different players have reported experiencing this bug already.

![brope1](https://user-images.githubusercontent.com/42658874/105619001-45fe0c00-5dab-11eb-8989-5c320030b90f.jpg)

![brope2](https://user-images.githubusercontent.com/42658874/105619003-49919300-5dab-11eb-996a-ec0c3e84d6ee.jpg)

**Comment by AtheistNMRiH** [comment] 2021-01-24 06:21
Reproducible, after some testing I've found that last changes in extraction entities breaks parenting nmrih_extract_preview to other entities (this bug never happend before)
nmo_boardwalk's nmrih_extract_preview is parented to func_tracktrain (helicopter) and fires output OnEndFollow to point_template, which spawns rope. But now it doesn't fire this output because camera doesn't work at all (you see spooky eyes of your character and don't see extraction)

**Comment by TheUnstableNutcase** [comment] 2021-01-24 08:08
> Reproducible, after some testing I've found that last changes in extraction entities breaks parenting nmrih_extract_preview to other entities (this bug never happend before)
> nmo_boardwalk's nmrih_extract_preview is parented to func_tracktrain (helicopter) and fires output OnEndFollow to point_template, which spawns rope. But now it doesn't fire this output because camera doesn't work at all (you see spooky eyes of your character and don't see extraction)

A possible fix could be to make the camera follow a path_track instead of being patented to the helicopter

**Comment by AtheistNMRiH** [comment] 2021-01-24 08:53
yeah, but some custom maps can have parented cameras too, and some of them could be abandoned, so we need general solution

**Comment by felis-catus** [comment] 2021-01-24 15:03
Confirmed regression from 1.11.3's code changes.

**Comment by felis-catus** [comment] 2021-01-24 20:12
src-r4964 fixes extraction preview not firing OnEndFollow.

**Comment by felis-catus** [comment] 2021-02-10 00:22
Fixed in src-r5000.

**Closed by felis-catus** 2021-02-10 00:22 UTC
Labels: Priority: Severe, Status: Assigned, Type: Code
