### ISSUE TITLE
[nmo_cabin] Stuck after using welder in kitchen.

### ISSUE THREAD

**Issue by Keldorn074** [nmrih/source-game#473] opened 2013-11-05 03:56 UTC
I picked  up this report on the steam community hub, rather then explain to him to use github , much easier to just screenshot and post it here.

![u88ntitled](https://f.cloud.github.com/assets/3848484/1470943/2070ba3e-45ce-11e3-82eb-b3284a30a299.jpg)

**Comment by AtheistNMRiH** [comment] 2018-02-08 11:18
same as #284 , need to be closed, check 284 for updates

**Comment by Bubka3** [comment] 2018-02-09 09:13
**Duplicate Closure**
This issue has been closed because it has already been reported under a previous issue ID.
Please follow the issue below for further updates.

Duplicate of #284

**Closed by Bubka3** 2018-02-09 09:13 UTC
