### ISSUE TITLE
[public-1.10] Inconsistent shove registration

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#831] opened 2018-01-22 14:33 UTC
The video speaks for itself:
https://www.youtube.com/watch?v=vOmJ4uBFx10

I really don't know what any other info can be gathered about this issue, but it happens at least once in every NMRiH match I've played, and those are many. If there's anything else I can test for, leave a comment.

**Comment by DDysphie** [comment] 2018-06-06 12:51
There appear to be 2 separate issues here

Looks like:
Schedule `ZOMBIE_CHASE_ENEMY` fails before every **delayed** shove
Console output:
![20180606092141_1](https://user-images.githubusercontent.com/11559683/41039195-164ee610-696f-11e8-859e-9f48dbf041b0.jpg)


Schedule `ZOMBIE_GRAB_ENEMY` fails before every **ignored** shove
Console output:
![dllhost_2018-06-06_09-45-37](https://user-images.githubusercontent.com/11559683/41039080-b5498104-696e-11e8-81b1-c753e79e7d64.png)

**Comment by Holycrapjimhox** [comment] 2018-09-17 20:00
Re-tested on r-8856. Shoving seems to be more consistent in general. Delayed shoves are fixed, but on some instances, when zombies are not playing any animations, shoves tend to get ignored. This usually happens when a player gets too close to a zombie to trigger an attack (also when they are standing on uneven terrain where pathing is difficult) . The usual response is for the zombie to immediately attack, but occasionally they will stop playing all animations for less than a second, and then attack. Most attempts at shoving the zombie when this occurs result in a missing shove.

Dysphie also shared some more info regarding this issue on the tester's channel:
![sdsdsd](https://user-images.githubusercontent.com/35630284/45646851-dec54400-ba9a-11e8-840f-2dc0247a83c4.png)
And here's her demo:
[bulli5.zip](https://github.com/nmrih/source-game/files/2390065/bulli5.zip)

**Comment by Dysphie** [comment] 2018-09-17 20:46
Yeah, I'd agree it's better now. That regression is pretty insignificant. I'm not sure whether this also tackles delayed reactions to shots (pretty rare), since it also uses shove_react, maybe.

**Comment by Dysphie** [comment] 2018-11-15 04:59
Adding video: https://youtu.be/mJZlUwb_WyI

**Comment by dysphie** [comment] 2020-02-05 18:35
Easy repro steps for delayed shoves, using crawler: https://youtu.be/W_DSUz35YA8

**Comment by felis-catus** [comment] 2020-02-17 00:09
Speculative fix added in src-r4874. (Add 'shoved' as forced interrupt condition)

**Comment by Holycrapjimhox** [comment] 2020-02-17 01:08
I ran a quick test and these are the results:

• Shamblers: they seem to register every shove, on corners, on their backs, while trying to navigate tight spaces. The only time they don’t register shoves is when you shove them right as they are climbing up or down and they “space out”, idling, searching for a target.

• Runners: they behaved exactly like shamblers (phasing out when climbing up or down), with the exception that sometimes if you shove them right as they were turning to attack you (while standing still), on the side of their bodies or the back, they will ignore shoves.

• Crawlers: shoving them from the back doesn’t seem to work at all, while other shoves done at an angle sometimes failed. I couldn’t get them to phase out while climbing up or down, but it’s possible. The biggest change here is that they didn’t phase out on my while I shoved them from the front.

• Kids: they behaved exactly like shamblers (phasing out when climbing up or down). I only tested on the girl, cause the boy keeps t-posing.

Note: I used nmo_suzhou's spawn room geometry to test shoves when zombies are against columns or walls and I used the benches to force them to climb up.

**Comment by Holycrapjimhox** [comment] 2020-02-17 01:20
Note: the zombies "spacing out" is exactly what Dysphie described here:

"what i did notice is that pushing a zombie while they're climbing down an object gets stuck trying to play SHOVED_REACT"

**Comment by felis-catus** [comment] 2020-02-17 13:42
Fix appears to work, closing as resolved.

**Closed by felis-catus** 2020-02-17 13:42 UTC
Labels: Priority: Normal, Status: Assigned, Type: Code

**Comment by Holycrapjimhox** [comment] 2020-02-17 14:19
Note: according to the game's code, shoving crawlers from the back is disabled since they have angle checks for when to register a shove. Also, runners not registering shoves from behind seems to be a separate issue regarding hit registration itself, since the schedules don't fail anymore. It needs another post with repro steps.
