### ISSUE TITLE
[public-1.14.0] Crash server kernel on custom map: Dimension Time

### ISSUE THREAD

**Issue by MAGISTER-PD2OR** [nmrih/source-game#1536] opened 2024-11-02 17:08 UTC
I try found bug and yes there dump with sourcemod plugin accelerator:
https://crash.limetech.org/bcddoo4dkpwu

You can see there crash server with KERNELBASE.dll + 0x159c84

Map crash only at end when train incomming and transition:
https://steamcommunity.com/sharedfiles/filedetails/?id=2489653968

For quick test there need:
Install map on server and load with sv_cheats 1, developer 1

When join to client:
setpos 2680 -263 -838

After retry in console server until you get objective "Use the clockwork to travel through time":
script ObjectiveManager.StartNextObjective()

Travel to date October 19 to see train when solve puzzle with clock.
And there crash when go on train or before.

**Comment by MAGISTER-PD2OR** [comment] 2024-11-02 17:12
Ah and souremod, metamod, with accelerator versions:
sourcemod-1.12.0-git7165-windows
mmsource-1.11.0-git1155-windows
accelerator-2.5.0-git138-cd575aa-windows

**Comment by MAGISTER-PD2OR** [comment] 2024-11-02 17:14
I also try without sourcemod and metamod, too crash server.
Only with accelerator i found details why crash my server.

**Comment by felis-catus** [comment] 2024-11-02 17:27
Duplicate of #1527

**Closed as completed by felis-catus** 2024-11-02 17:27 UTC
