### ISSUE TITLE
charged melee

### ISSUE THREAD

**Issue by WoodyInvincible** [nmrih/source-game#442] opened 2013-10-25 05:13 UTC
after testing all melee weapons,the hatchet has an issue.the charged attack never seems to hit no matter how close.furthermore,any time u miss a charged attack at a zombie , the usual "2 hit normal swing kill" weapons will be 1 hit ko at the same zombie where u missed the charged melee .eg , i missed my baseball bat charge at the zombie, then i follow it up with one normal swing.it killed it despite normally swinging twice to kill it

**Comment by Fersigal** [comment] 2018-01-18 18:06
Neither of those are bugs

**Comment by AtheistNMRiH** [comment] 2018-02-18 06:40
duplicate of #419

**Comment by Bubka3** [comment] 2018-02-20 03:38
**Duplicate Closure**
This issue has been closed because it has already been reported under a previous issue ID.
Please follow the issue below for further updates.

Duplicate of #419

**Closed by Bubka3** 2018-02-20 03:38 UTC
