### ISSUE TITLE
[r8885] Barricades play sound after being cancelled

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#1070] opened 2019-01-11 00:01 UTC
r8883 set out to fix not being able to cancel barricades but left this as a result.

Steps to reproduce:
1) Start barricading a wall
2) Cancel barricade
3) Noise still plays even though the player is not hammering anything

Video: https://www.youtube.com/watch?v=cSoXG2UWS3s

**Comment by Ryan-nmrih** [comment] 2019-01-11 04:57
The sound also continues playing if you die. That part isn't a regression though because it's been present pre 1.10.

**Comment by felis-catus** [comment] 2024-11-25 18:26
Fixed in dev-r10133.

**Closed by felis-catus** 2024-11-25 18:26 UTC
Labels: Status: Reviewed, Type: Code, Priority: Minimal
