### ISSUE TITLE
Objective Wielding Bug (nmo_cabin)

### ISSUE THREAD

**Issue by Scripts18** [nmrih/source-game#284] opened 2013-08-03 16:55 UTC
Happened near the end right when we get to unwield a door to get outside, I unwielded the door but right after I did I clicked again to wield or unwield and it actually did and I was then stuck in an open door.

Note : Screenshots are not working for some reason...

**Comment by AtheistNMRiH** [comment] 2018-02-08 16:38
couldn't reproduce, looks like it was fixed in previous versions, need to be closed

**Closed** 2018-02-09 09:14 UTC
