### ISSUE TITLE
survivors spawn problem on nms_arpley

### ISSUE THREAD

**Issue by EdmundKemper** [nmrih/source-game#1060] opened 2018-12-10 18:22 UTC
Hi so there is a problem when survivors spawn/respawn in the bridge , sometimes they respawn inside parts of the bridge like this 
https://prnt.sc/lt7734
and they cant walk or run they are stuck there ,i wish this can be fixed 

P.D: sorry for my english

**Comment by AtheistNMRiH** [comment] 2018-12-11 07:51
#733

**Comment by felis-catus** [comment] 2019-09-14 16:41
Duplicate of #733, closed.

**Closed by felis-catus** 2019-09-14 16:41 UTC
