### ISSUE TITLE
[public-1.12.3] physics bugs

### ISSUE THREAD

**Issue by MAGISTER-PD2OR** [nmrih/source-game#1345] opened 2022-08-31 16:21 UTC
On random maps happen sometime:
Ignoring unreasonable position (-2739.010010,2948.998779,-16384.191406) from vphysics! (entity r2)

Then when join on current server physics broken and props drop under map or just flying around on ground after drop.

**Comment by felis-catus** [comment] 2022-08-31 18:46
Closing as it's unlikely to be caused by native code.

**Closed by felis-catus** 2022-08-31 18:46 UTC
