### ISSUE TITLE
Spectator mode: SKS plays Beretta 92's firing sound

### ISSUE THREAD

**Issue by DDysphie** [nmrih/source-game#873] opened 2018-02-26 07:39 UTC
Both variants of the SKS sound like a Beretta 92 in spectator camera.

**Comment by Bubka3** [comment] 2018-02-26 12:25
**Duplicate Closure**
This issue has been closed because it has already been reported under a previous issue ID.
Please follow the issue below for further updates.

Duplicate of #767

**Closed by Bubka3** 2018-02-26 12:25 UTC
