### ISSUE TITLE
[public-1.12.0] Objective related inventory items don't change glow when approached by player

### ISSUE THREAD

**Issue by TheUnstableNutcase** [nmrih/source-game#1241] opened 2021-11-01 21:31 UTC
Objective related inventory items don't seem to change their glow when approached by the player despite the player having enough inventory space.

![20211101131330_1](https://user-images.githubusercontent.com/42658874/139744644-ccc250e1-2c4b-4896-8418-9dc33b9e9c69.jpg)

![20211101131412_1](https://user-images.githubusercontent.com/42658874/139744655-f03ba109-1977-4e8e-9096-139d878856f3.jpg)

![20211031222431_1](https://user-images.githubusercontent.com/42658874/139744712-be46a366-34bb-4070-8c42-72af99cee474.jpg)

When approached by a player with enough inventory space, the glow around the item should be green, however this is not the case

**Comment by felis-catus** [comment] 2021-11-01 21:46
Not a bug, we decided to keep the objective glow instead of overriding it with inventory colors, see #967. Closing.

**Closed by felis-catus** 2021-11-01 21:46 UTC
