### ISSUE TITLE
[public-1.11.1] Using weapons, ammo, and other items to make the zombie incapacitated

### ISSUE THREAD

**Issue by T4WER2** [nmrih/source-game#1143] opened 2020-05-02 03:31 UTC
Hello again. Again, I apologize for the fact that you may not understand me at some points, because I do not know English well and I think it is better for me to write with the help of a translator.
   A couple of hours ago, my friend (Pla3) called me to show me a strange bug that he accidentally discovered, we did not know how to apply it exactly, but a little experimenting I realized how it can be easily used, in fact, everything is elementary and anyone can easily repeat it.
   To do this, you need to find any item that you can take to your inventory and stand directly on it. In the video, I used my fists to feel the middle, and so you can use the sight and so on. You can also get up on various entities, elevators, and so on..

https://www.youtube.com/watch?v=gwJYb0CykO4
   
The fact is that when a player stands on some entity mostly from the inventory ( except prop_static and some others probably don't know, we haven't found out yet), the zombies start to blunt and just stand still, not doing anything to you, this is a very serious bug, and the players don't know about it yet. By the way, the bug works with any items from the inventory, even with bullets... It doesn't seem to work with quest items, but it depends on the type of entity. We'll try to keep it a secret until it's too late. We checked this bug on different servers and on different maps (official and from other players) so unfortunately it works absolutely everywhere.
  And more.. This is not about the bug. After the update, you wanted to make sure that the zombies did not bite through the doors, but you also did that now they can not break various physical objects. Boxes and other items and now they can be easily used against zombies, This is especially noticeable on some of my maps(I did them before the update and did not count on this outcome of events). I certainly do not resent it, but it just became less realistic and the zombies become less dangerous. (this is my opinion)
   I rarely come here and complain about bugs, but this case did not allow me to stay away and I hope that you will fix it as soon as possible. Good luck and stay safe!

**Comment by AtheistNMRiH** [comment] 2020-07-11 15:44
![1](https://user-images.githubusercontent.com/11333747/87227806-68a87480-c3c7-11ea-98ce-77220d108413.jpg)
![2](https://user-images.githubusercontent.com/11333747/87227809-6e05bf00-c3c7-11ea-9640-ecc06e506f8e.jpg)
It is probably regression, because in previous versions zombies could hit you if you stand on these entities (door = prop_physics, elevator platform = func_tracktrain? (can't check it right now)

**Comment by Holycrapjimhox** [comment] 2020-07-11 18:11
I seem to remember that there were changes on zombies attacking when stuck in front of a physics object. This may be related to: #785

**Comment by felis-catus** [comment] 2020-07-20 18:40
Fixed in src-r4934.

**Closed by felis-catus** 2020-07-20 18:40 UTC
Labels: Priority: Normal, Status: Assigned, Type: Code
