### ISSUE TITLE
[public-1.11.1] NMRiH random crashes

### ISSUE THREAD

**Issue by Sourveid** [nmrih/source-game#1139] opened 2020-04-02 21:26 UTC
After around patch 1.11 my game has been experiencing random crashes for some reason, there is no specific map or action that i need to do in order to happen due to being totally random from what i could tell. No window telling me about a missing file or anything appears after the game closing itself, it simply just drops me out of the game. I am not 100% sure if addons from the workshop could be causing it because i play with almost no addons at all and the ones i ocassionally use make very subtle changes to be real suspicious about it.
[dumps.zip.zip](https://github.com/nmrih/source-game/files/4423748/dumps.zip.zip)

**Comment by TheUnstableNutcase** [comment] 2020-04-03 01:02
This issue is almost the exact same as #1133, these 2 issues should probably be merged

**Comment by Holycrapjimhox** [comment] 2020-04-03 01:03
Not necessarily. The crashes can be caused by different issues. Until that's determined, they should be left as separate post.

**Comment by felis-catus** [comment] 2020-04-03 21:15
Unfortunately these dumps point to engine modules, which we can't debug. Closing.

**Closed by felis-catus** 2020-04-03 21:15 UTC
Labels: OS: Windows, Priority: Normal, Status: Reviewed, Type: Crash
