### ISSUE TITLE
shove animation bug

### ISSUE THREAD

**Issue by porkchops4lunch** [nmrih/source-game#494] opened 2013-11-19 06:03 UTC
https://www.youtube.com/watch?v=NKBmX8bZbcM

Happened during a normal play through of NoTLD, nothing out of the ordinary happened before this occured.

**Comment by Fersigal** [comment] 2018-04-17 13:41
![image](https://user-images.githubusercontent.com/11538773/38872714-397adc6c-4254-11e8-9574-7cbb60cf3731.png)
![image](https://user-images.githubusercontent.com/11538773/38872725-3ed44158-4254-11e8-8bb9-49f11188345e.png)
![image](https://user-images.githubusercontent.com/11538773/38872911-bbadd7de-4254-11e8-960b-a4b9ac937842.png)
![image](https://user-images.githubusercontent.com/11538773/38872927-c651d690-4254-11e8-911d-a5e92cb9a031.png)
![image](https://user-images.githubusercontent.com/11538773/38873290-acea7c2e-4255-11e8-918f-edaed0f06eaa.png)
I could not reproduce this in the dev build even after 10 zombies grabbing me, i'm not sure if this is still possible, maybe the steps to reproduce it seems to be very specific. Also this issue is 5 years old so it might've been fixed ever since

**Comment by Holycrapjimhox** [comment] 2018-04-17 16:57
It's still present on public build, I've seen it several times. But this is also one of those "once in a blue moon" type of bugs, very rare, incredibly hard to reproduce and hard to understand its cause.

**Comment by felis-catus** [comment] 2021-09-23 16:12
Closing, no repro steps. Possible duplicate of #19.

**Closed by felis-catus** 2021-09-23 16:12 UTC
Labels: Status: Reviewed, Type: Code, Priority: Minimal
