### ISSUE TITLE
Hammer with board running animation bug

### ISSUE THREAD

**Issue by alingsteve** [nmrih/source-game#814] opened 2016-12-24 13:59 UTC
Not a big problem , but yea.
If you run when equipping a hammer and holding a barricade , it looks sort of awful

**Comment by Fersigal** [comment] 2018-01-18 15:56
Also works for Chainsaw / abrasive saw

**Comment by Winning117** [comment] 2018-04-01 22:37
Duplicate of [#59](https://github.com/nmrih/source-game/issues/59), needs to be closed.

**Closed** 2018-04-03 05:39 UTC
Labels: Status: Reviewed, Type: Animation
