### ISSUE TITLE
Nmo_Cabin Safe Bug

### ISSUE THREAD

**Issue by Wazanator** [nmrih/source-game#725] opened 2015-04-24 03:25 UTC
When you shoot the family picture and quickly try to open safe it glitches and after few seconds the safe doors opens.

https://www.youtube.com/watch?v=AYWV8_5LmoU

**Comment by AtheistNMRiH** [comment] 2018-02-16 16:43
maybe fixed in r8729, I couldn't reproduce it, need more testing

**Comment by Winning117** [comment] 2018-03-27 01:22
Confirmed fixed in src-r4367/dev-r8764.

**Closed** 2018-04-01 00:08 UTC
Labels: Priority: Normal, Status: Completed, Type: Map
