### ISSUE TITLE
Walking away from zombies biting you

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#948] opened 2018-04-12 07:37 UTC
Version: public and src-r4405/dev-r8785

I have noticed some weird behavior with zombies which allowed me to walk away from crawlers while they were biting me without me shoving them (https://www.youtube.com/watch?v=Mz0svwKV9mg). I have also been able to walk away from a shambler that was biting me, but further testing needs to be done to find out what triggers it (https://www.youtube.com/watch?v=tpsziOJs8o8).

**Note:** "I think the issue is related to zombies calling CNMRiH_Player::OnGrabbedEnd even when they don't have the player grabbed. I assume this function is what restores the player's ability to move. After a zombie has grabbed a player, they never forget who they last had grabbed. This means that whenever they are shoved or attempt to grab another player, they call the OnGrabbedEnd function for the original player." -Ryan

**Comment by felis-catus** [comment] 2018-04-17 10:49
Zombies shouldn't start biting you if you were already being grabbed, fixed this behavior in src-r4421.

**Comment by Winning117** [comment] 2018-04-29 22:58
Not fixed in src-r4435/dev-r8793.

**Comment by Winning117** [comment] 2020-02-16 20:34
Multiple zombies can still grab you https://www.youtube.com/watch?v=ymXkTnHD3rM

**Comment by Winning117** [comment] 2020-02-18 00:09
[Relevant video](https://www.youtube.com/watch?v=7BoKFtKeuDw)

**Comment by Winning117** [comment] 2020-02-18 00:47
This seems to be a side effect of multiple zombies grabbing you at once which is mentioned in #1112.

**Comment by essbuh** [comment] 2020-02-18 01:35
This should be fixed by src-r4882

**Closed by essbuh** 2020-02-18 01:35 UTC
Labels: Priority: Minimal, Status: Assigned, Type: Code

**Comment by Holycrapjimhox** [comment] 2020-02-19 04:58
Could not reproduce this in r8975. May need more testing though since this issue wasn't very common during normal gameplay.
