### ISSUE TITLE
Incorrect Zombie Hitboxes

### ISSUE THREAD

**Issue by acwass** [nmrih/source-game#1199] opened 2021-07-18 23:52 UTC
Hey, when using melee, it becomes apparent that when you hit and are aiming at the head, with a fully charged shot from any melee that should instant kill them, it instead hits in the neck or torso doing minimal damage, instead of the max damage instant shot it should do, this is a big problem as its pretty much random and can be infuriating as your shot that should've killed the zombie, instead does minimal damage and they kill you instead.

**Comment by felis-catus** [comment] 2021-07-19 01:59
Duplicate of #947

**Closed by felis-catus** 2021-07-19 01:59 UTC
