### ISSUE TITLE
Standing inside certain objects causes zombies not to attack

### ISSUE THREAD

**Issue by DDysphie** [nmrih/source-game#847] opened 2018-01-29 20:47 UTC
Steps to reproduce:

1. Find
 a) Supply drop (`item_inventory_box`)
 b) Safe zone repair box (`nmrih_safezone_supply`)
 c) Health station  (`nmrih_health_station`)
2. Stand inside it

Zombies will get close but never attack you

Screenshots:
![20180129175244_1](https://user-images.githubusercontent.com/11559683/35533804-6453f6c2-051d-11e8-9c2b-869af38682f1.jpg)

![20180129175653_1](https://user-images.githubusercontent.com/11559683/35533979-d440f7aa-051d-11e8-8943-82c5f546f89b.jpg)

A [community plugin](https://forums.alliedmods.net/showthread.php?p=2573434) fixes this by setting their `m_CollisionGroup` to `1` or `0` accordingly (line #1387 of qol.sp)

**Comment by Fersigal** [comment] 2018-01-29 20:51
Representation of pictures:
![20180129205818_1](https://user-images.githubusercontent.com/11538773/35533636-71c6f036-053e-11e8-86ec-f909a6b3ee8f.jpg)
http://steamcommunity.com/sharedfiles/filedetails/?id=1285464161

**Comment by Fersigal** [comment] 2018-01-29 22:10
#378 #358

**Comment by Bubka3** [comment] 2018-02-26 18:56
**Duplicate Closure**
This issue has been closed because it has already been reported under a previous issue ID.
Please follow the issue below for further updates.

Duplicate of #378

**Closed by Bubka3** 2018-02-26 18:56 UTC
Labels: Status: Reviewed, Type: Code
