### ISSUE TITLE
[public] Grenade plays missing sound when thrown

### ISSUE THREAD

**Issue by DDysphie** [nmrih/source-game#968] opened 2018-05-07 16:51 UTC
```Failed to load sound ")weapons\firearms\exp_frag\frag_throw.wav", file probably missing from disk/repository```

Should either remove the call or use `{hl2_sound_misc_dir}/weapons/slam/throw.wav`

**Comment by AtheistNMRiH** [comment] 2018-05-07 17:04
duplicate of #854 
but your post has solution :p

**Closed** 2018-05-07 17:13 UTC
