### ISSUE TITLE
nms_campblood - zone c missing gun spawns

### ISSUE THREAD

**Issue by Bubka3** [nmrih/source-game#869] opened 2018-02-21 21:26 UTC
```
This is totally unrelated, but please fix nms_campblood! None of the guns spawn in the cage in Zone C (the bathrooms) anymore. It was my group's favorite survival map but now we never play it because all the guns seem to have mysteriously vanished,
and one supply drop halfway through isn't enough to sate us with this new lack of guns.
```

Forum escalation from: http://steamcommunity.com/app/224260/discussions/0/2860219962099395783/#c1693788202020406166
_If you have any questions contact the linked author through Steam_

**Comment by AtheistNMRiH** [comment] 2018-02-22 08:12
duplicate of #801 :stuck_out_tongue:

**Closed** 2018-02-23 16:18 UTC
Labels: map, reviewed
