### ISSUE TITLE
Showing zones problem on nms_northway(1.09.3)

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#705] opened 2015-03-26 06:32 UTC
![nms_northway0000](https://cloud.githubusercontent.com/assets/11333747/6841379/23247180-d3bc-11e4-9f33-8559709c9de3.jpg)
Sometimes it doesn't show all zones. I dont know how to reproduce, it just happened randomly

**Comment by Bubka3** [comment] 2018-01-22 21:05
Duplicate of #531 

Please follow that issue for all future updates.

**Closed by Bubka3** 2018-01-22 21:05 UTC
Labels: duplicate, map, reviewed
