### ISSUE TITLE
(dev) nmo_lakeside (map bugs)

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#952] opened 2018-04-14 23:01 UTC
NOTE: some of them may have been already fixed, and some of them are duplicates of Winning's post: https://github.com/nmrih/source-game/issues/950

**• Item Softlocks**
1) Ways to bug Garage key/Sidedoor key:
![20180329105952_1](https://user-images.githubusercontent.com/35630284/38773134-81618cb8-401c-11e8-9e30-35806d04c601.jpg)
FIXED
![20180329110209_1](https://user-images.githubusercontent.com/35630284/38773135-8184dc04-401c-11e8-8ea2-48fa1c2bc19b.jpg)
FIXED
![20180329110214_1](https://user-images.githubusercontent.com/35630284/38773136-81a61a0e-401c-11e8-83e0-aaba8414c8ae.jpg)
FIXED
![20180329111043_1](https://user-images.githubusercontent.com/35630284/38773137-81c5fcd4-401c-11e8-835f-36346899970c.jpg)
FIXED
![20180329111052_1](https://user-images.githubusercontent.com/35630284/38773138-81e838e4-401c-11e8-8289-d6bdd0d6508a.jpg)
FIXED
![20180329111101_1](https://user-images.githubusercontent.com/35630284/38773139-82087e06-401c-11e8-8430-0bce36d56fc0.jpg)
FIXED
![20180329111400_1](https://user-images.githubusercontent.com/35630284/38773140-82284d8a-401c-11e8-99bb-018a25471cbc.jpg)
FIXED
![20180329111422_1](https://user-images.githubusercontent.com/35630284/38773141-824a02d6-401c-11e8-8684-70095719ee3e.jpg)
FIXED
![20180329114329_1](https://user-images.githubusercontent.com/35630284/38773143-8298e16c-401c-11e8-8c63-d67888f1b89c.jpg)
Technically fixed, but now you can't break the glass with anything, but you can break the glass that is next to it.
![20180329114643_1](https://user-images.githubusercontent.com/35630284/38773144-82b9422c-401c-11e8-9d66-150e64fe0330.jpg)
FIXED
![20180330130136_1](https://user-images.githubusercontent.com/35630284/38773146-8304164e-401c-11e8-900a-32e320be76ba.jpg)
FIXED

2) Ways to bug Gascan/Propane tank
![20180330130702_1](https://user-images.githubusercontent.com/35630284/38773168-a7f57240-401c-11e8-9984-0a415bfbefc7.jpg)
FIXED
![20180330130747_1](https://user-images.githubusercontent.com/35630284/38773169-a816f3de-401c-11e8-972c-83692909948d.jpg)
FIXED
![20180330130832_1](https://user-images.githubusercontent.com/35630284/38773170-a8376510-401c-11e8-94b4-947aab1bb518.jpg)
FIXED
![20180330130846_1](https://user-images.githubusercontent.com/35630284/38773171-a85a076e-401c-11e8-8af8-4dc090a895e6.jpg)
FIXED

**• Other Softlocks:**
![20180411210901_1](https://user-images.githubusercontent.com/35630284/38773211-84dbc326-401d-11e8-8332-66f2eb0591ad.jpg)
![20180411210925_1](https://user-images.githubusercontent.com/35630284/38773212-84fada86-401d-11e8-88e4-340c9e918d34.jpg)
![20180411211119_1](https://user-images.githubusercontent.com/35630284/38773213-851a5154-401d-11e8-96e3-e9de0bf0ef55.jpg)
The code is no longer highlighted on the ground like in public build. I haven't been able to find it at all, both white markers point at the keypad, and the red marker pointed to the corpse on the last picture, no code at all.
FIXED

**• Possible softlock spots:**
These are spots where I couldn't actually bug items, but someone else might, since they are mostly holes in the vphysclip clusters
![20180329110538_1](https://user-images.githubusercontent.com/35630284/38773242-04520516-401e-11e8-9590-7e8c4cb5c34c.jpg)
FIXED
![20180329110652_1](https://user-images.githubusercontent.com/35630284/38773243-04898ad6-401e-11e8-844c-9541300b0658.jpg)
FIXED
![20180329114953_1](https://user-images.githubusercontent.com/35630284/38773244-04ab7632-401e-11e8-8909-e2d787b85d8f.jpg)
FIXED

**• Map oddities and regressions:**
1)
![20180330125732_1](https://user-images.githubusercontent.com/35630284/38773180-f2f62a46-401c-11e8-8f08-6a44ac9a17a5.jpg)
![20180330125746_1](https://user-images.githubusercontent.com/35630284/38773181-f31783da-401c-11e8-936c-f95369c5c3d6.jpg)
(I don't remember if this is present in the public build, but it doesn't make sense that the two corpses appear at the same time, when the key is near only one of them)
FIXED

2)
![20180330133725_1](https://user-images.githubusercontent.com/35630284/38773187-1370fad0-401d-11e8-8945-fe9473f96285.jpg)
![20180330133727_1](https://user-images.githubusercontent.com/35630284/38773188-13962eb8-401d-11e8-95ac-c97175f65e62.jpg)
The prop clip makes props look like they are floating.
FIXED

3)
![20180330134552_1](https://user-images.githubusercontent.com/35630284/38773192-28317ae4-401d-11e8-8522-caaa5e50c213.jpg)
This table is blocking the way to the stairs, but it looks as if you can easily move it away manually and go through. Adding more blockage there would have more sense.
FIXED

4)
![20180330135800_1](https://user-images.githubusercontent.com/35630284/38773205-56960788-401d-11e8-9707-e165751cb0d2.jpg)
Zombies can spawn on top of some trees
NO WAY TO TEST IF IT'S FIXED OR NOT

5) 
![20180411212005_1](https://user-images.githubusercontent.com/35630284/38773228-c8e9ba6e-401d-11e8-8a4d-21409b0ad120.jpg)
The laptop/door glow can still be seen during the cutscene, but only for a brief moment.
FIXED

6)
![20180411210129_1](https://user-images.githubusercontent.com/35630284/38773251-28850e38-401e-11e8-84d9-10e4f7660c26.jpg)
You could fall down to the basement and get stuck there permanently on older dev versions and on public build. Now that's fixed, but the door still opens up when you turn on the generator, and there is an invisible wall that blocks your movement. This happened on the "make your way through the tunnel" set of objectives.
FIXED

**• Lighting and detail regressions:**
In general, the map has primitive looking lighting compared to the public build. It would be nice if the details could be recreated again.

Some examples on dev version:
![20180411210112_1](https://user-images.githubusercontent.com/35630284/38773265-8a26bed4-401e-11e8-8645-d78640bce33f.jpg)
FIXED
![20180411210119_1](https://user-images.githubusercontent.com/35630284/38773266-8a489a68-401e-11e8-9967-7edaa4e6f15e.jpg)
FIXED

**Comment by AtheistNMRiH** [comment] 2018-04-17 14:46
most of them were fixed in previous versions, others fixed in r8788

**Comment by Holycrapjimhox** [comment] 2018-04-22 15:55
MORE BUGS (r4405/8789):

1) Key ring appears twice when you don't get the garage key on the outside.
![20180422112936_1](https://user-images.githubusercontent.com/35630284/39096772-8c3deadc-462a-11e8-901f-b65cfece2e7c.jpg)
![20180422112943_1](https://user-images.githubusercontent.com/35630284/39096773-8c5de9f4-462a-11e8-93ed-e13e71ddf8fb.jpg)

2) Regression: electric breaker doesn't have animation
![20180422113231_1](https://user-images.githubusercontent.com/35630284/39096784-bd021a80-462a-11e8-8d32-fcec70907d24.jpg)

3) Still not fixed regression: The 3 underground breakers still don't play the activation sound
![20180422113302_1](https://user-images.githubusercontent.com/35630284/39096800-d53d653c-462a-11e8-8016-5a4feb6a838c.jpg)

4) Annoying clipping next to the railings close to the bridge:
![20180422113326_1](https://user-images.githubusercontent.com/35630284/39096808-e6461dce-462a-11e8-9f60-8e958476f78c.jpg)
![20180422113335_1](https://user-images.githubusercontent.com/35630284/39096809-e666709c-462a-11e8-825c-79a298e7dcd7.jpg)

5) New welder position which lets players locate and pick it up really easily. All welders should remain inside the container to force them to explore, like in the public version:
![20180422113442_1](https://user-images.githubusercontent.com/35630284/39096827-118b1c00-462b-11e8-8af9-0ff93792d3ac.jpg)

6) Minor nitpick: It should spell "Find key to THE cellar"
![20180422113604_1](https://user-images.githubusercontent.com/35630284/39096830-280c11b4-462b-11e8-87fb-697019970f23.jpg)

7) The softlock here was fixed, but not in a correct way. The glass is now unbreakable, and it's right next to a glass that is breakable. A vphysclip should be added there, and make the window breakable.
![20180422113710_1](https://user-images.githubusercontent.com/35630284/39096835-334fb7ba-462b-11e8-90c0-d9e7662fb2e8.jpg)

8) Parts of the boat are still not solid:
![20180422114055_1](https://user-images.githubusercontent.com/35630284/39096862-5ad127b0-462b-11e8-8eba-d0a4e34f6c92.jpg)
![20180422114047_1](https://user-images.githubusercontent.com/35630284/39096861-5ab054ea-462b-11e8-98ba-2153b61db23d.jpg)ç

9) Unnecessary clipping: the key will just stop there. It's off-putting if you get the objective where there is no fence on the bridge.
![20180422115055_1](https://user-images.githubusercontent.com/35630284/39096875-93f59e7c-462b-11e8-8785-171267b0dcf4.jpg)

10) The helicopter disappears out of thin air. Maybe make it go somewhere the player can't see, or make it keep going further to the sea until out of sight.
![20180422115450_1](https://user-images.githubusercontent.com/35630284/39096892-b7fcc836-462b-11e8-9b6d-4424891f0e66.jpg)
![20180422115450_2](https://user-images.githubusercontent.com/35630284/39096894-b81c68da-462b-11e8-8627-40364474ba5b.jpg)

11) You can still see through the world next to the entrance to the cellar:
![20180422120604_1](https://user-images.githubusercontent.com/35630284/39096920-dfec1da6-462b-11e8-91fe-d04e201bfec4.jpg)

12) The propane tank now deals damage. This is perfectly fine, but then all other tanks on other maps should deal damage, for example nmo_fema. I was told that you couldn't change that due to messing with the map balance, but it really doesn't make any sense.
![20180422120618_1](https://user-images.githubusercontent.com/35630284/39096942-17715980-462c-11e8-965f-1d09529b389e.jpg)

13) The laptop glow still doesn't disappear during the cutscene:
![20180422120744_1](https://user-images.githubusercontent.com/35630284/39096943-1c6aa216-462c-11e8-8ed7-4dffcd022f1b.jpg)

14) You can see through the door in the tunnel:
![20180422121103_1](https://user-images.githubusercontent.com/35630284/39096949-3acc4e4e-462c-11e8-8e17-6f198b1f1fc0.jpg)

**Comment by AtheistNMRiH** [comment] 2018-04-23 05:50
3) it doesn't directly play sound in public neither, it activates generators near button and start plays "machine noise" sound, not a bug
5) it is old welder position, iirc it was highlited in public too but with white colour so it was harder to see it, maybe I'll remove glow anyway
6) we don't have nmos file for lakeside, won't fix :(
9) iirc you mentioned in old post that floating key isn't good too (when you have broken bridge in one of scenarios) so I guess coolz added that clip (not sure if it is his clip) to prevent floating key
12) check nmo_fema, propane tank deals damage too
13) it is probably code issue, if you don't stay near radio or laptop you won't see glowing, I don't really want to mess with final i/o system to try to fix that

**Comment by AtheistNMRiH** [comment] 2018-04-25 16:12
fixed in r8791

**Closed** 2018-05-06 15:04 UTC
Labels: Priority: Minimal, Status: Completed, Type: Map
