### ISSUE TITLE
[public-1.12.1] "Squirrel VM stack not consistent" with EntitiesInBox 

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1276] opened 2021-12-30 19:33 UTC
test.nut:
```cpp
EntitiesInBox(someTable, 16, Vector(-1000, -1000, -1000), Vector(1000, 1000, 1000), MASK_SOLID);
```

![image](https://user-images.githubusercontent.com/11559683/147782669-834cc7e3-4185-48ad-ab67-3e91ae1ce317.png)

tested in nmo_dev_world_felis

**Comment by felis-catus** [comment] 2022-01-18 11:35
Fixed in src-r5812.

PS. This issue appears to be caused by a faulty script, following is an example how the function should be used:

```cpp
table <- []; // array
EntitiesInBox(table, 16, Vector(-1000, -1000, -1000), Vector(1000, 1000, 1000), MASK_SOLID);

// print results
for (local i = 0; i < table.len(); i++)
	printl(table[i]);

```

**Closed by felis-catus** 2022-01-18 11:35 UTC
Labels: Status: Reviewed, Type: Code, Priority: Minimal
