### ISSUE TITLE
No military crawler 

### ISSUE THREAD

**Issue by Fersigal** [nmrih/source-game#796] opened 2016-02-21 11:18 UTC
![2016-02-21_00001](https://cloud.githubusercontent.com/assets/11538773/13202280/2b0a3ab8-d895-11e5-9fbe-bfeb18db8a15.jpg)
![2016-02-21_00002](https://cloud.githubusercontent.com/assets/11538773/13202281/2b0aa8c2-d895-11e5-95fb-ee42b12be6f1.jpg)
![2016-02-21_00003](https://cloud.githubusercontent.com/assets/11538773/13202283/2b0ed410-d895-11e5-837e-6d2af05f4323.jpg)
![2016-02-21_00004](https://cloud.githubusercontent.com/assets/11538773/13202282/2b0d9afa-d895-11e5-9d0e-55cb71b1c8ed.jpg)

**Comment by Bubka3** [comment] 2018-01-14 16:44
# Feature Request
It appears the issue you've created is a feature request.
This tracker is not the appropriate forum for most feature requests.

For suggestions or to provide feedback regarding the game, please visit the forums:
http://steamcommunity.com/app/224260/discussions/

**Comment by Fersigal** [comment] 2018-01-20 13:41
Nah thinking about it, a military crawler wouldn't make sense

**Comment by Bubka3** [comment] 2018-01-27 14:28
Actually, it appears this is something that was intended since the models support a crawler form. My apologizes, this issue is now reopened.

QOL reference:

```sourcepawn
/**
 * Setup DHooks on a new zombie and allow random chance for National Guard
 * to spawn as a crawler.
 */
public void Hook_DHookZombieSpawn(int zombie)
{
    // Random chance for National Guard to spawn as crawlers.
    if (IsNationalGuard(zombie) && GetURandomFloat() < g_qol_national_guard_crawler_chance.FloatValue)
    {
        SetEntData(zombie, g_offset_is_torso, 1, 1);
        SetEntData(zombie, g_offset_is_crawler, 1, 1);

        // Resize zombie's hull. (Necessary for right collision and so their grab works).
        SetEntProp(zombie, Prop_Data, "m_eHull", HULL_CRAWLER);
        SDKCall(g_sdkcall_set_hull_size, zombie, true);

        // Use customizable health.
        int health = g_qol_national_guard_crawler_health.IntValue;
        if (health < 1)
        {
            health = 1;
        }
        SetEntProp(zombie, Prop_Data, "m_iHealth", health);
    }

    DHookZombie(zombie);
}
```

**Comment by felis-catus** [comment] 2018-01-28 12:14
Fixed in code commit r4230.

**Comment by Bubka3** [comment] 2018-02-08 06:43
**Resolved Closure**
This issue has been closed as it has been resolved in the current dev build.
It will be available to the public in the next steam release. Thanks for reporting!

Additional comments: crawlers present dev-r8722, windows

**Closed by Bubka3** 2018-02-08 06:43 UTC
Labels: code, resolved, reviewed
